# Generated by Django 6.0.2 on 2026-02-22 20:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("govuk", "0026_rename_home_tables"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomiseSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_background_color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional hero background color in hex, for example #b5cd1e.",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid hex color, for example #1d70b8 or #fff.",
                                regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                            )
                        ],
                    ),
                ),
                (
                    "hero_text_color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional hero text color in hex, for example #ffffff.",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid hex color, for example #1d70b8 or #fff.",
                                regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                            )
                        ],
                    ),
                ),
                (
                    "extra_css",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional additional CSS appended after hero overrides.",
                    ),
                ),
                (
                    "extra_js",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional additional JavaScript.",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customise",
                "verbose_name_plural": "Customise",
            },
        ),
    ]
