# Generated by Django 6.0.2 on 2026-02-22 21:30

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0027_customisesettings'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdDSAKeySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Signing keys',
                'verbose_name_plural': 'Signing keys',
            },
        ),
        migrations.CreateModel(
            name='EdDSAKeyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('key_id', models.CharField(blank=True, help_text='Optional key ID (kid). If blank, it is generated from the public key.', max_length=64)),
                ('public_key', models.TextField(help_text='Ed25519 public key in PEM format.')),
                ('private_key', models.TextField(blank=True, help_text='Ed25519 private key in PEM format. Stored securely and hidden after save.')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary key pair used for signing new tokens.')),
                ('settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_pairs', to='govuk.eddsakeysettings')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('settings', 'key_id'), name='govuk_eddsa_key_id_unique_per_site'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('settings',), name='govuk_single_primary_eddsa_key_per_site')],
            },
        ),
    ]
