# Generated by Django 6.0.2 on 2026-02-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0028_eddsakeysettings_eddsakeypair'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdiscoverysource',
            name='send_signed_bearer_jwt',
            field=models.BooleanField(default=False, help_text="When enabled, sends an Authorization bearer token signed using this site's primary key from Settings > Signing keys.", verbose_name='Send signed bearer JWT'),
        ),
    ]
