# Generated by Django 6.0.2 on 2026-02-25 00:57

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0031_taglistingspage_hide_last_updated'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovukRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Optional key used for links, for example digital-forensics-analyst.', max_length=120, unique=True)),
                ('title', models.CharField(help_text='Role name, for example Digital forensics analyst.', max_length=255)),
                ('body', wagtail.fields.RichTextField(blank=True, help_text='Optional summary for this role.')),
                ('levels', wagtail.fields.StreamField([('level', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Role level name, for example Associate digital forensics analyst.', 'max_length': 255, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol'], 'required': False}), 2: ('wagtail.snippets.blocks.SnippetChooserBlock', ('govuk.GovukSkill',), {'required': True}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('awareness', 'Awareness'), ('working', 'Working'), ('practitioner', 'Practitioner'), ('expert', 'Expert')]}), 4: ('wagtail.blocks.StructBlock', [[('skill', 2), ('level', 3)]], {'icon': 'pick', 'label': 'Skill requirement'}), 5: ('wagtail.blocks.ListBlock', (4,), {'help_text': 'Add one or more skill requirements for this role level.', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('skills', 5)]], {'icon': 'user', 'label': 'Role level'})}, help_text='Role levels and their associated skills.')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['title', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='GovukSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Optional key used for links, for example forensics.', max_length=120, unique=True)),
                ('title', models.CharField(help_text='Skill name, for example Forensics.', max_length=255)),
                ('body', wagtail.fields.RichTextField(blank=True, help_text='Short description of the skill.')),
                ('awareness_points', wagtail.fields.StreamField([('point', 0)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'max_length': 500, 'required': False, 'rows': 3})}, help_text='Optional awareness-level points.')),
                ('working_points', wagtail.fields.StreamField([('point', 0)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'max_length': 500, 'required': False, 'rows': 3})}, help_text='Optional working-level points.')),
                ('practitioner_points', wagtail.fields.StreamField([('point', 0)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'max_length': 500, 'required': False, 'rows': 3})}, help_text='Optional practitioner-level points.')),
                ('expert_points', wagtail.fields.StreamField([('point', 0)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'max_length': 500, 'required': False, 'rows': 3})}, help_text='Optional expert-level points.')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['title', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='RolePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('enable_hero_styling', models.BooleanField(default=False, help_text='When enabled, this page uses hero styling.', verbose_name='Enable hero styling')),
                ('enable_combined_service_navigation_and_hero_styling', models.BooleanField(default=False, help_text='When enabled, this page uses a combined service navigation and hero styling.', verbose_name='Enable combined service navigation and hero styling')),
                ('hero_title', models.CharField(blank=True, help_text='Optional hero heading. If blank, the page title is used.', max_length=255)),
                ('hero_intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('enable_free_text_heading_navigation', models.BooleanField(default=False, help_text='Show free text in a two-thirds and one-third layout with an automatic clickable heading list.', verbose_name='Enable sidebar heading navigation')),
                ('selected_roles', wagtail.fields.StreamField([('role', 0)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', ('govuk.GovukRole',), {'required': False})}, help_text='Select one or more roles to render on this page.')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
