# Generated by Django 6.0.2 on 2026-02-25 01:05

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0032_govukrole_govukskill_rolepage'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsAZPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('enable_hero_styling', models.BooleanField(default=False, help_text='When enabled, this page uses hero styling.', verbose_name='Enable hero styling')),
                ('enable_combined_service_navigation_and_hero_styling', models.BooleanField(default=False, help_text='When enabled, this page uses a combined service navigation and hero styling.', verbose_name='Enable combined service navigation and hero styling')),
                ('hero_title', models.CharField(blank=True, help_text='Optional hero heading. If blank, the page title is used.', max_length=255)),
                ('hero_intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('enable_free_text_heading_navigation', models.BooleanField(default=False, help_text='Show free text in a two-thirds and one-third layout with an automatic clickable heading list.', verbose_name='Enable sidebar heading navigation')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
