# Generated by Django 6.0.2 on 2026-02-25 01:25

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0033_skillsazpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='govuk.rolepage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_page_tagged_items', to='govuk.govuktag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rolepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='govuk.RolePageTag', to='govuk.GovukTag', verbose_name='Tags'),
        ),
    ]
