# Generated by Django 6.0.2 on 2026-02-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0035_alter_sectionpage_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='taglistingspage',
            name='sort_order',
            field=models.CharField(choices=[('newest_first', 'Newest first'), ('alphabetical_az', 'Alphabetical (A-Z)')], default='newest_first', help_text='Choose how listing cards are ordered.', max_length=20, verbose_name='Sort order'),
        ),
    ]
