# Generated by Django 6.0.2 on 2026-03-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0036_taglistingspage_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdiscoverysource',
            name='sync_source',
            field=models.BooleanField(default=False, help_text='When enabled, this source will be synced from the remote content and any missing items will be hidden.', verbose_name='Sync source and hide missing'),
        ),
        migrations.AddField(
            model_name='externalcontentitem',
            name='private',
            field=models.BooleanField(default=False, help_text='Set this item private, accessible to any logged-in users.'),
        ),
    ]
