# Generated by Django 6.0.2 on 2026-03-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0037_contentdiscoverysource_sync_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdiscoverysource',
            name='consume_tags',
            field=models.BooleanField(default=False, help_text='When enabled, if the remote source content has tags they will be applied to the discovered content.', verbose_name='Consume tags from remote source'),
        ),
        migrations.AlterField(
            model_name='contentdiscoverysource',
            name='sync_source',
            field=models.BooleanField(default=False, help_text='When enabled, this remote source will be synced and any missing items previously discovered will be hidden. Disabled (default) will just keep adding discovered content.', verbose_name='Sync from remote source and hide any missing'),
        ),
    ]
