# Generated by Django 6.0.2 on 2026-03-05 11:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0039_taglistingspage_enable_source_display_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionpage',
            name='rows',
            field=wagtail.fields.StreamField([('row', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional heading for this row section.', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional header image for this card.', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('cover', 'Cover'), ('contain', 'Contain')], 'help_text': 'How the header image should fit inside the card.'}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol'], 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional button text.', 'max_length': 80, 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional URL for the button, for example /apply or https://example.gov.uk/apply.', 'max_length': 500, 'required': False}), 7: ('wagtail.snippets.blocks.SnippetChooserBlock', ('govuk.GovukTag',), {'required': False}), 8: ('wagtail.blocks.ListBlock', (7,), {'help_text': 'Optional tags for this card.', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('title', 1), ('image', 2), ('image_fit', 3), ('text', 4), ('link_text', 5), ('link_url', 6), ('tags', 8)]], {'icon': 'doc-full', 'label': 'Card'}), 10: ('wagtail.blocks.ListBlock', (9,), {'help_text': 'Add between 1 and 60 cards in this row.', 'max_num': 60, 'min_num': 1}), 11: ('wagtail.blocks.StructBlock', [[('heading', 0), ('cards', 10)]], {'icon': 'placeholder', 'label': 'Row section'})}, help_text='Add one or more row sections. Each row can contain up to 60 cards.'),
        ),
    ]
