# Generated by Django 6.0.2 on 2026-03-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0040_alter_sectionpage_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='author',
            field=models.CharField(blank=True, default='', help_text='Optional author name displayed above the main content.', max_length=255),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='show_last_updated_date',
            field=models.BooleanField(default=False, help_text='Show the page last updated date above the main content.', verbose_name='Show last updated date'),
        ),
        migrations.AddField(
            model_name='rolepage',
            name='author',
            field=models.CharField(blank=True, default='', help_text='Optional author name displayed above the main content.', max_length=255),
        ),
        migrations.AddField(
            model_name='rolepage',
            name='show_last_updated_date',
            field=models.BooleanField(default=False, help_text='Show the page last updated date above the main content.', verbose_name='Show last updated date'),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='author',
            field=models.CharField(blank=True, default='', help_text='Optional author name displayed above the main content.', max_length=255),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='show_last_updated_date',
            field=models.BooleanField(default=False, help_text='Show the page last updated date above the main content.', verbose_name='Show last updated date'),
        ),
        migrations.AddField(
            model_name='skillsazpage',
            name='author',
            field=models.CharField(blank=True, default='', help_text='Optional author name displayed above the main content.', max_length=255),
        ),
        migrations.AddField(
            model_name='skillsazpage',
            name='show_last_updated_date',
            field=models.BooleanField(default=False, help_text='Show the page last updated date above the main content.', verbose_name='Show last updated date'),
        ),
        migrations.AddField(
            model_name='taglistingspage',
            name='author',
            field=models.CharField(blank=True, default='', help_text='Optional author name displayed above the main content.', max_length=255),
        ),
        migrations.AddField(
            model_name='taglistingspage',
            name='show_last_updated_date',
            field=models.BooleanField(default=False, help_text='Show the page last updated date above the main content.', verbose_name='Show last updated date'),
        ),
    ]
