# Generated by Django 6.0.2 on 2026-03-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0041_contentpage_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taglistingspage',
            name='show_private_cards_to_non_authenticated_users',
            field=models.BooleanField(default=False, help_text='Show cards for private pages to users who are not signed in. Opening those pages still requires signing in.', verbose_name='Show private cards to non-authenticated users'),
        ),
    ]
