# Generated by Django 6.0.2 on 2026-03-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("govuk", "0042_taglistingspage_show_private_cards_to_non_authenticated_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="customisesettings",
            name="header_logo",
            field=models.CharField(
                choices=[("govuk", "GOV.UK"), ("uk-government", "UK Government")],
                default="govuk",
                help_text="Select the header logo to display.",
                max_length=20,
            ),
        ),
    ]
