# Generated by Django 6.0.2 on 2026-03-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0043_customisesettings_header_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customisesettings',
            name='show_site_name_in_search_box',
            field=models.BooleanField(default=False, help_text='Include the site name in the header search label and placeholder.'),
        ),
    ]
