# Generated by Django 6.0.2 on 2026-03-05 22:43

from urllib.parse import urlparse

import wagtail.fields
from django.db import migrations


def _build_site_contexts(Site, Page):
    site_rows = list(
        Site.objects.values_list("id", "root_page_id", "hostname", "port")
    )
    root_page_ids = [root_page_id for _, root_page_id, _, _ in site_rows]
    root_url_paths = dict(
        Page.objects.filter(id__in=root_page_ids).values_list("id", "url_path")
    )

    contexts = {}
    for site_id, root_page_id, hostname, port in site_rows:
        contexts[site_id] = {
            "hostname": (hostname or "").lower(),
            "port": port,
            "root_url_path": root_url_paths.get(root_page_id) or "",
        }
    return contexts


def _candidate_url_path(root_url_path, site_path):
    cleaned_path = (site_path or "/").split("?", 1)[0].split("#", 1)[0]
    if cleaned_path == "/":
        return root_url_path

    relative_path = cleaned_path.lstrip("/")
    if relative_path and not relative_path.endswith("/"):
        relative_path = f"{relative_path}/"
    return f"{root_url_path}{relative_path}"


def _matching_site_path(legacy_url, site_context):
    parsed = urlparse(legacy_url)
    if parsed.scheme in {"http", "https"} and parsed.netloc:
        parsed_hostname = (parsed.hostname or "").lower()
        if parsed_hostname and parsed_hostname != site_context["hostname"]:
            return None
        parsed_port = parsed.port
        site_port = site_context["port"]
        if parsed_port and site_port and parsed_port != site_port:
            return None
        return parsed.path or "/"

    if not parsed.scheme and not parsed.netloc and legacy_url.startswith("/"):
        return parsed.path or "/"

    return None


def _external_url(legacy_url, site_context):
    parsed = urlparse(legacy_url)
    if parsed.scheme and parsed.netloc:
        return legacy_url

    if legacy_url.startswith("//"):
        return f"https:{legacy_url}"

    if legacy_url.startswith("/") and site_context["hostname"]:
        scheme = "https" if site_context["port"] == 443 else "http"
        port = site_context["port"]
        port_suffix = f":{port}" if port not in {80, 443} else ""
        query = f"?{parsed.query}" if parsed.query else ""
        fragment = f"#{parsed.fragment}" if parsed.fragment else ""
        return (
            f"{scheme}://{site_context['hostname']}{port_suffix}"
            f"{parsed.path or '/'}{query}{fragment}"
        )

    return legacy_url


def migrate_footer_links_to_page_chooser_and_url_block(apps, schema_editor):
    del schema_editor
    FooterSettings = apps.get_model("govuk", "FooterSettings")
    Site = apps.get_model("wagtailcore", "Site")
    Page = apps.get_model("wagtailcore", "Page")

    site_contexts = _build_site_contexts(Site, Page)
    page_id_cache = {}

    for footer_settings in FooterSettings.objects.all().iterator():
        raw_blocks = getattr(footer_settings.footer_links, "raw_data", None) or []
        updated_blocks = []
        has_changes = False

        for block in raw_blocks:
            if not isinstance(block, dict) or block.get("type") != "link":
                updated_blocks.append(block)
                continue

            value = block.get("value")
            if not isinstance(value, dict) or "url" not in value:
                updated_blocks.append(block)
                continue

            legacy_url = (value.get("url") or "").strip()
            site_context = site_contexts.get(footer_settings.site_id) or {
                "hostname": "",
                "port": None,
                "root_url_path": "",
            }
            page_id = None

            if legacy_url and site_context["root_url_path"]:
                site_path = _matching_site_path(legacy_url, site_context)
                if site_path:
                    lookup_key = (
                        footer_settings.site_id,
                        _candidate_url_path(site_context["root_url_path"], site_path),
                    )
                    if lookup_key not in page_id_cache:
                        page_id_cache[lookup_key] = Page.objects.filter(
                            url_path=lookup_key[1]
                        ).values_list("id", flat=True).first()
                    page_id = page_id_cache[lookup_key]

            new_value = {
                "title": value.get("title"),
                "page": page_id,
                "external_url": "" if page_id else _external_url(legacy_url, site_context),
            }

            updated_block = dict(block)
            updated_block["value"] = new_value
            updated_blocks.append(updated_block)
            has_changes = True

        if has_changes:
            footer_settings.footer_links = updated_blocks
            footer_settings.save(update_fields=["footer_links"])


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0044_customisesettings_show_site_name_in_search_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='footer_links',
            field=wagtail.fields.StreamField([('link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Use an absolute external URL like https://www.gov.uk/help.', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('page', 1), ('external_url', 2)]], {})}, help_text='Links shown in the footer support links list.'),
        ),
        migrations.RunPython(
            migrate_footer_links_to_page_chooser_and_url_block,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
