# Generated by Django 6.0.2 on 2026-03-05 23:23

from urllib.parse import urlparse

import wagtail.fields
from django.db import migrations


def _build_site_contexts(Site, Page):
    site_rows = list(
        Site.objects.values_list("id", "root_page_id", "hostname", "port")
    )
    root_page_ids = [root_page_id for _, root_page_id, _, _ in site_rows]
    root_page_rows = Page.objects.filter(id__in=root_page_ids).values_list(
        "id", "path", "url_path"
    )
    root_page_info = {
        page_id: {"path": path or "", "url_path": url_path or ""}
        for page_id, path, url_path in root_page_rows
    }

    contexts = {}
    for site_id, root_page_id, hostname, port in site_rows:
        root_page = root_page_info.get(root_page_id) or {}
        contexts[site_id] = {
            "hostname": (hostname or "").lower(),
            "port": port,
            "root_path": root_page.get("path") or "",
            "root_url_path": root_page.get("url_path") or "",
        }
    ordered_contexts = sorted(
        contexts.items(),
        key=lambda row: len(row[1]["root_path"]),
        reverse=True,
    )
    return contexts, ordered_contexts


def _site_context_for_page_path(page_path, ordered_contexts):
    for site_id, context in ordered_contexts:
        root_path = context.get("root_path") or ""
        if root_path and (page_path or "").startswith(root_path):
            return site_id, context
    return None, {"hostname": "", "port": None, "root_url_path": ""}


def _candidate_url_path(root_url_path, site_path):
    cleaned_path = (site_path or "/").split("?", 1)[0].split("#", 1)[0]
    if cleaned_path == "/":
        return root_url_path

    relative_path = cleaned_path.lstrip("/")
    if relative_path and not relative_path.endswith("/"):
        relative_path = f"{relative_path}/"
    return f"{root_url_path}{relative_path}"


def _matching_site_path(legacy_url, site_context):
    parsed = urlparse(legacy_url)
    if parsed.scheme in {"http", "https"} and parsed.netloc:
        parsed_hostname = (parsed.hostname or "").lower()
        if parsed_hostname and parsed_hostname != site_context["hostname"]:
            return None
        parsed_port = parsed.port
        site_port = site_context["port"]
        if parsed_port and site_port and parsed_port != site_port:
            return None
        return parsed.path or "/"

    if not parsed.scheme and not parsed.netloc and legacy_url.startswith("/"):
        return parsed.path or "/"

    return None


def _external_url(legacy_url, site_context):
    parsed = urlparse(legacy_url)
    if parsed.scheme and parsed.netloc:
        return legacy_url

    if legacy_url.startswith("//"):
        return f"https:{legacy_url}"

    if legacy_url.startswith("/") and site_context["hostname"]:
        scheme = "https" if site_context["port"] == 443 else "http"
        port = site_context["port"]
        port_suffix = f":{port}" if port not in {80, 443} else ""
        query = f"?{parsed.query}" if parsed.query else ""
        fragment = f"#{parsed.fragment}" if parsed.fragment else ""
        return (
            f"{scheme}://{site_context['hostname']}{port_suffix}"
            f"{parsed.path or '/'}{query}{fragment}"
        )

    return legacy_url


def migrate_section_page_rows_to_link_block(apps, schema_editor):
    del schema_editor
    SectionPage = apps.get_model("govuk", "SectionPage")
    Site = apps.get_model("wagtailcore", "Site")
    Page = apps.get_model("wagtailcore", "Page")

    _, ordered_site_contexts = _build_site_contexts(Site, Page)
    page_id_cache = {}

    for section_page in SectionPage.objects.all().iterator():
        raw_rows = getattr(section_page.rows, "raw_data", None) or []
        updated_rows = []
        has_changes = False

        site_id, site_context = _site_context_for_page_path(
            getattr(section_page, "path", ""),
            ordered_site_contexts,
        )

        for row in raw_rows:
            if not isinstance(row, dict) or row.get("type") != "row":
                updated_rows.append(row)
                continue

            row_value = row.get("value")
            if not isinstance(row_value, dict):
                updated_rows.append(row)
                continue

            cards = row_value.get("cards")
            if not isinstance(cards, list):
                updated_rows.append(row)
                continue

            updated_cards = []
            row_changed = False

            for card in cards:
                if not isinstance(card, dict):
                    updated_cards.append(card)
                    continue

                card_value = card.get("value")
                if not isinstance(card_value, dict):
                    updated_cards.append(card)
                    continue

                has_legacy_keys = "link_text" in card_value or "link_url" in card_value
                if not has_legacy_keys:
                    updated_cards.append(card)
                    continue

                new_card_value = dict(card_value)
                legacy_link_text = (new_card_value.pop("link_text", "") or "").strip()
                legacy_link_url = (new_card_value.pop("link_url", "") or "").strip()

                if legacy_link_url:
                    page_id = None
                    if site_id and site_context["root_url_path"]:
                        site_path = _matching_site_path(legacy_link_url, site_context)
                        if site_path:
                            lookup_key = (
                                site_id,
                                _candidate_url_path(site_context["root_url_path"], site_path),
                            )
                            if lookup_key not in page_id_cache:
                                page_id_cache[lookup_key] = Page.objects.filter(
                                    url_path=lookup_key[1]
                                ).values_list("id", flat=True).first()
                            page_id = page_id_cache[lookup_key]

                    link_title = (
                        legacy_link_text
                        or (new_card_value.get("title") or "").strip()
                        or "Read more"
                    )
                    new_card_value["link"] = {
                        "title": link_title,
                        "page": page_id,
                        "external_url": (
                            "" if page_id else _external_url(legacy_link_url, site_context)
                        ),
                    }

                updated_card = dict(card)
                updated_card["value"] = new_card_value
                updated_cards.append(updated_card)
                row_changed = True
                has_changes = True

            if row_changed:
                updated_row_value = dict(row_value)
                updated_row_value["cards"] = updated_cards
                updated_row = dict(row)
                updated_row["value"] = updated_row_value
                updated_rows.append(updated_row)
                continue

            updated_rows.append(row)

        if has_changes:
            section_page.rows = updated_rows
            section_page.save(update_fields=["rows"])


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0045_alter_footersettings_footer_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionpage',
            name='rows',
            field=wagtail.fields.StreamField([('row', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional heading for this row section.', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional header image for this card.', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('cover', 'Cover'), ('contain', 'Contain')], 'help_text': 'How the header image should fit inside the card.'}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol'], 'required': False}), 5: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'help_text': 'Use an absolute external URL like https://www.gov.uk/help.', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 1), ('page', 5), ('external_url', 6)]], {'required': False}), 8: ('wagtail.snippets.blocks.SnippetChooserBlock', ('govuk.GovukTag',), {'required': False}), 9: ('wagtail.blocks.ListBlock', (8,), {'help_text': 'Optional tags for this card.', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 1), ('image', 2), ('image_fit', 3), ('text', 4), ('link', 7), ('tags', 9)]], {'icon': 'doc-full', 'label': 'Card'}), 11: ('wagtail.blocks.ListBlock', (10,), {'help_text': 'Add between 1 and 60 cards in this row.', 'max_num': 60, 'min_num': 1}), 12: ('wagtail.blocks.StructBlock', [[('heading', 0), ('cards', 11)]], {'icon': 'placeholder', 'label': 'Row section'})}, help_text='Add one or more row sections. Each row can contain up to 60 cards.'),
        ),
        migrations.RunPython(
            migrate_section_page_rows_to_link_block,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
