# Generated by Django 6.0.2 on 2026-03-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0046_alter_sectionpage_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='enable_tag_display',
            field=models.BooleanField(default=False, help_text='Show tag labels on cards.', verbose_name='Enable tag display'),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='enable_tag_filter',
            field=models.BooleanField(default=False, help_text='Show a tag filter control above the cards.', verbose_name='Enable tag filter'),
        ),
    ]
