# Generated by Django 6.0.2 on 2026-03-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0047_sectionpage_enable_tag_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='show_page_content_metadata',
            field=models.BooleanField(default=False, help_text='Show page metadata above the main content.', verbose_name='Show page content metadata'),
        ),
        migrations.AddField(
            model_name='rolepage',
            name='show_page_content_metadata',
            field=models.BooleanField(default=False, help_text='Show page metadata above the main content.', verbose_name='Show page content metadata'),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='show_page_content_metadata',
            field=models.BooleanField(default=False, help_text='Show page metadata above the main content.', verbose_name='Show page content metadata'),
        ),
        migrations.AddField(
            model_name='skillsazpage',
            name='show_page_content_metadata',
            field=models.BooleanField(default=False, help_text='Show page metadata above the main content.', verbose_name='Show page content metadata'),
        ),
        migrations.AddField(
            model_name='taglistingspage',
            name='show_page_content_metadata',
            field=models.BooleanField(default=False, help_text='Show page metadata above the main content.', verbose_name='Show page content metadata'),
        ),
    ]
