# Generated by Django 6.0.3 on 2026-03-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0048_contentpage_show_page_content_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasebannersettings',
            name='phase_text',
            field=models.CharField(default='This is a new service.', help_text='Phase banners are used to show users your service is still being worked on.', max_length=500),
        ),
    ]
