# Generated by Django 6.0.7 on 2026-07-28 10:02

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0049_phasebannersettings_phase_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovukChangelogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date the change was published.')),
                ('change_type', models.CharField(blank=True, default='', help_text='Optional label, for example New role or Skills updated.', max_length=100)),
                ('note', wagtail.fields.RichTextField(help_text='What changed.')),
                ('live', models.BooleanField(default=True, help_text='Unpublish to hide this entry without deleting it.', verbose_name='Published')),
                ('role', models.ForeignKey(blank=True, help_text='Leave blank for a site-wide update.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changelog_entries', to='govuk.govukrole')),
                ('skill', models.ForeignKey(blank=True, help_text='Leave blank for a site-wide update.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changelog_entries', to='govuk.govukskill')),
            ],
            options={
                'verbose_name': 'Changelog entry',
                'verbose_name_plural': 'Changelog entries',
                'ordering': ['-date', 'pk'],
            },
        ),
    ]
