# Generated by Django 6.0.7 on 2026-08-04 10:22

from django.db import migrations, models


def carry_placements_forward(apps, schema_editor):
    """Map the old booleans onto the new location dropdowns.

    Previously a single flag moved both the service name and the search into
    the service navigation, and the sign in link could only be shown or hidden
    in the navigation. Preserve each site's existing appearance.
    """
    CustomiseSettings = apps.get_model("govuk", "CustomiseSettings")

    to_update = []
    for settings in CustomiseSettings.objects.all():
        in_navigation = settings.show_service_name_in_navigation
        settings.service_name_location = "navigation" if in_navigation else "header"
        settings.search_location = "navigation" if in_navigation else "header"
        settings.sign_in_location = "hidden" if settings.hide_sign_in_link else "navigation"
        to_update.append(settings)

    if to_update:
        CustomiseSettings.objects.bulk_update(
            to_update,
            ["service_name_location", "search_location", "sign_in_location"],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0050_site_header_and_phase_banner_wording'),
    ]

    operations = [
        migrations.AddField(
            model_name='customisesettings',
            name='search_location',
            field=models.CharField(choices=[('header', 'Header bar'), ('navigation', 'Service navigation'), ('hidden', 'Hidden')], default='header', help_text='Where the search box appears.', max_length=20),
        ),
        migrations.AddField(
            model_name='customisesettings',
            name='service_name_location',
            field=models.CharField(choices=[('header', 'Header bar'), ('navigation', 'Service navigation')], default='header', help_text='Where the service name appears.', max_length=20),
        ),
        migrations.AddField(
            model_name='customisesettings',
            name='sign_in_location',
            field=models.CharField(choices=[('header', 'Header bar'), ('navigation', 'Service navigation'), ('hidden', 'Hidden')], default='navigation', help_text='Where the sign in and sign out links appear. Choose Hidden for sites where visitors never sign in.', max_length=20),
        ),
        migrations.RunPython(carry_placements_forward, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='customisesettings',
            name='hide_sign_in_link',
        ),
        migrations.RemoveField(
            model_name='customisesettings',
            name='show_service_name_in_navigation',
        ),
    ]
