# Generated by Django 6.0.7 on 2026-07-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0050_govukchangelogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='govukrole',
            name='family',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Role family used to group roles, for example Data.', max_length=255),
        ),
    ]
