# Generated by Django 6.0.7 on 2026-07-28 11:53

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0051_govukrole_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='govukrole',
            name='is_senior_civil_service',
            field=models.BooleanField(default=False, help_text='Senior Civil Service roles have no role levels. Their skills are listed flat, with examples of leadership.', verbose_name='Senior Civil Service role'),
        ),
        migrations.AddField(
            model_name='govukrole',
            name='scs_grades',
            field=wagtail.fields.StreamField([('grade', 0)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('scs1', 'SCS 1'), ('scs2', 'SCS 2'), ('scs3', 'SCS 3')], 'required': False})}, help_text='Grades this role is most often performed at.', verbose_name='Indicative Senior Civil Service grades'),
        ),
        migrations.AddField(
            model_name='govukrole',
            name='scs_skills',
            field=wagtail.fields.StreamField([('skill', 0)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', ('govuk.GovukSkill',), {'required': False})}, help_text='Skills required by this role, with no proficiency level.', verbose_name='Senior Civil Service skills'),
        ),
        migrations.AddField(
            model_name='govukskill',
            name='is_senior_civil_service',
            field=models.BooleanField(default=False, help_text='Senior Civil Service skills describe leadership rather than ascending proficiency levels.', verbose_name='Senior Civil Service skill'),
        ),
        migrations.AddField(
            model_name='govukskill',
            name='leadership_points',
            field=wagtail.fields.StreamField([('point', 0)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'max_length': 500, 'required': False, 'rows': 3})}, help_text='Examples of leadership using this skill, for Senior Civil Service skills.', verbose_name='Examples of leadership'),
        ),
    ]
