# Generated by Django 6.0.7 on 2026-07-28 21:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0052_govukrole_is_senior_civil_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govukrole',
            name='levels',
            field=wagtail.fields.StreamField([('level', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Role level name, for example Associate digital forensics analyst.', 'max_length': 255, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol'], 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('ao', 'AO (Administrative Officer)'), ('eo', 'EO (Executive Officer)'), ('heo', 'HEO (Higher Executive Officer)'), ('seo', 'SEO (Senior Executive Officer)'), ('g7', 'G7 (Grade 7)'), ('g6', 'G6 (Grade 6)'), ('scs1', 'SCS 1 (Senior Civil Service 1)'), ('scs2', 'SCS 2 (Senior Civil Service 2)'), ('scs3', 'SCS 3 (Senior Civil Service 3)')], 'required': False}), 3: ('wagtail.blocks.ListBlock', (2,), {'help_text': 'Grades this role level is most often performed at. Leave empty to hide the sentence, as management-track levels do.', 'label': 'Indicative Civil Service job grades', 'required': False}), 4: ('wagtail.snippets.blocks.SnippetChooserBlock', ('govuk.GovukSkill',), {'required': True}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('awareness', 'Awareness'), ('working', 'Working'), ('practitioner', 'Practitioner'), ('expert', 'Expert')]}), 6: ('wagtail.blocks.StructBlock', [[('skill', 4), ('level', 5)]], {'icon': 'pick', 'label': 'Skill requirement'}), 7: ('wagtail.blocks.ListBlock', (6,), {'help_text': 'Add one or more skill requirements for this role level.', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('grades', 3), ('skills', 7)]], {'icon': 'user', 'label': 'Role level'})}, help_text='Role levels and their associated skills.'),
        ),
        migrations.AlterField(
            model_name='govukrole',
            name='scs_grades',
            field=wagtail.fields.StreamField([('grade', 0)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('scs1', 'SCS 1 (Senior Civil Service 1)'), ('scs2', 'SCS 2 (Senior Civil Service 2)'), ('scs3', 'SCS 3 (Senior Civil Service 3)')], 'required': False})}, help_text='Grades this role is most often performed at.', verbose_name='Indicative Senior Civil Service grades'),
        ),
    ]
