# Generated by Django 6.0.7 on 2026-08-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0053_alter_govukrole_levels_alter_govukrole_scs_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='customisesettings',
            name='hide_sign_in_link',
            field=models.BooleanField(default=False, help_text='Hide the sign in link, for sites where visitors never sign in.'),
        ),
        migrations.AddField(
            model_name='customisesettings',
            name='search_placeholder',
            field=models.CharField(blank=True, default='', help_text='Wording shown in the header search box, for example Search for roles or skills. Defaults to Search.', max_length=100),
        ),
        migrations.AddField(
            model_name='customisesettings',
            name='show_service_name_in_navigation',
            field=models.BooleanField(default=False, help_text='Show the site name and search in the service navigation bar rather than in the GOV.UK header, as GOV.UK services usually do.'),
        ),
        migrations.AddField(
            model_name='phasebannersettings',
            name='feedback_link_text',
            field=models.CharField(default='your feedback', help_text='Wording of the feedback link, shown between the two sentences.', max_length=100),
        ),
        migrations.AddField(
            model_name='phasebannersettings',
            name='phase_text_after',
            field=models.CharField(default='will help us to improve it.', help_text='Wording shown after the feedback link.', max_length=500),
        ),
    ]
