# Generated by Django 6.0.7 on 2026-07-30 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0053_alter_govukrole_levels_alter_govukrole_scs_grades'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieBannerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Show cookie banner across the site')),
                ('service_name', models.CharField(blank=True, default='', help_text='Name used in the banner heading, for example Government Digital and Data Profession Capability Framework. Defaults to the site name.', max_length=255)),
                ('analytics_text', models.CharField(default="We'd like to use analytics cookies so we can understand how you use the service and make improvements.", help_text='First paragraph, explaining what analytics cookies are for.', max_length=500)),
                ('essential_text', models.CharField(default="We also use essential cookies to remember if you've accepted analytics cookies.", help_text='Second paragraph, explaining the essential cookies.', max_length=500)),
                ('cookies_page_url', models.CharField(default='/cookies', help_text='Page describing the cookies used, where people can change their choice later.', max_length=500)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Cookie banner',
            },
        ),
    ]
