# Generated by Django 6.0.7 on 2026-08-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0054_site_header_and_phase_banner_wording'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='show_framework_updates',
            field=models.BooleanField(default=False, help_text='Show the changelog entries that are not tied to a single role or skill, with a last updated date above the page content.', verbose_name='Show framework updates'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='show_role_navigation',
            field=models.BooleanField(default=False, help_text='Show the list of roles grouped by family alongside the page, as the role pages do.', verbose_name='Show role navigation'),
        ),
    ]
