# Generated by Django 6.0.7 on 2026-08-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0055_content_page_role_navigation_and_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='show_framework_welcome',
            field=models.BooleanField(default=False, help_text="Show the framework's welcome text, with a contents list and the roles grouped by family for narrow screens.", verbose_name='Show framework welcome content'),
        ),
    ]
