# Generated by Django 6.0.7 on 2026-08-06 09:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0056_content_page_framework_welcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='framework_welcome_body',
            field=wagtail.fields.StreamField([('section', 4), ('skill_level_definitions', 13), ('section_break', 14), ('inset_text', 15)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section heading, for example How to use this framework.', 'max_length': 255}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Main section, listed in the contents'), ('h3', 'Sub-section, not listed in the contents')], 'help_text': 'Main sections appear in the contents list at the top of the page.'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional link target, for example capability-assessments. Defaults to the heading. Set one to keep existing links working if the heading is reworded.', 'max_length': 255, 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol'], 'help_text': "The section's prose."}), 4: ('wagtail.blocks.StructBlock', [[('heading', 0), ('level', 1), ('anchor', 2), ('body', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Skill level definitions', 'help_text': 'Table caption, read out by screen readers.', 'max_length': 255}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Skill level definitions', 'max_length': 255}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'What the level means', 'max_length': 255}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Level name, for example Awareness.', 'max_length': 100}), 9: ('wagtail.blocks.IntegerBlock', (), {'default': 1, 'help_text': 'How many of the 4 progress bar segments are filled, so awareness is 1 and expert is 4.', 'max_value': 4, 'min_value': 1}), 10: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol'], 'help_text': 'What someone at this level can do.'}), 11: ('wagtail.blocks.StructBlock', [[('name', 8), ('filled_segments', 9), ('description', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'help_text': 'One row per level, in ascending order.'}), 13: ('wagtail.blocks.StructBlock', [[('caption', 5), ('level_column_heading', 6), ('meaning_column_heading', 7), ('levels', 12)]], {}), 14: ('govuk.models.SectionBreakBlock', (), {}), 15: ('govuk.models.InsetTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol']})}, help_text="The welcome page's editorial content, shown when Show framework welcome content is switched on. The contents list is built from the main section headings.", verbose_name='Framework welcome content'),
        ),
    ]
