# Generated by Django 6.0.7 on 2026-08-17 15:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0059_capability_framework_service_navigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='govukrole',
            name='roles_that_could_lead_here',
            field=wagtail.fields.StreamField([('role', 0)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', ('govuk.GovukRole',), {'required': False})}, help_text='Roles someone might do before this one. Curated rather than derived from shared skills, and listed in the order given.', verbose_name='Roles that could lead to this role'),
        ),
    ]
