# Generated by Django 6.0.7 on 2026-08-18 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0061_seed_roles_that_could_lead_here'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapabilityFrameworkWordingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents_heading', models.CharField(default='Contents', help_text='Heading over the in-page contents links.', max_length=255)),
                ('last_updated_prefix', models.CharField(default='Last updated', help_text='Shown before the date the role was last changed.', max_length=255)),
                ('see_all_updates_link_text', models.CharField(default='See all updates', help_text='Wording of the link down to the updates section.', max_length=255)),
                ('scs_context_text', models.CharField(default='A specific {role} job can vary depending on the', help_text='Senior Civil Service roles only. Shown before the link to the context and challenges page. Use {role} for the role name.', max_length=255)),
                ('scs_context_link_text', models.CharField(default='context and challenges in your organisation', help_text='Wording of that link. A full stop follows it. Shown as plain text where the page it points at is missing.', max_length=255)),
                ('scs_skills_heading', models.CharField(default='Skills for {role}', help_text="Heading over a Senior Civil Service role's skills.", max_length=255)),
                ('scs_skills_intro', models.CharField(default='The {role} role will need to use digital and data skills to:', help_text='Sentence introducing the two points below it.', max_length=255)),
                ('scs_skills_leadership_point', models.CharField(default='be an effective digital and data leader', help_text='First of those points.', max_length=255)),
                ('scs_skills_context_point_text', models.CharField(default='operate in different contexts, depending', help_text='Second point, up to the link.', max_length=255)),
                ('scs_skills_context_point_link_text', models.CharField(default='on the context and challenges in your organisation', help_text='Rest of that point, linked to the context and challenges page.', max_length=255)),
                ('scs_skills_table_skill_heading', models.CharField(default='Skill', help_text='First column of the Senior Civil Service skills table.', max_length=255)),
                ('scs_skills_table_description_heading', models.CharField(default='Description, including examples of leadership', help_text='Second column of that table.', max_length=255)),
                ('scs_leadership_examples_heading', models.CharField(default='Examples of leadership using this skill:', help_text="Shown in that table above a skill's leadership points.", max_length=255)),
                ('role_grades_text', models.CharField(default='This role is often performed at the', help_text='Shown before the link to the job grades page, above the grades a Senior Civil Service role is done at.', max_length=255)),
                ('level_grades_text', models.CharField(default='This role level is most often performed at the', help_text='The same sentence for a role level rather than a whole role.', max_length=255)),
                ('job_grades_link_text', models.CharField(default='Civil Service job grade', help_text='Wording of that link. Shown as plain text where the job grades page is missing.', max_length=255)),
                ('grades_text_after', models.CharField(default='of:', help_text='Wording after that link, ending the sentence.', max_length=255)),
                ('role_levels_heading', models.CharField(default='{role} role levels', help_text="Heading over a role's levels. Here {role} keeps the role title's capitals, this being the start of a heading.", max_length=255)),
                ('level_skills_table_skill_heading', models.CharField(default='Skill', help_text="First column of a role level's skills table.", max_length=255)),
                ('level_skills_table_description_heading', models.CharField(default='Description', help_text='Second column of that table.', max_length=255)),
                ('skill_level_prefix', models.CharField(default='Level:', help_text='Shown before the level a role level needs a skill at.', max_length=255)),
                ('skill_level_scale_text', models.CharField(default='{level} is the {ordinal} of four ascending skill levels', help_text='Read aloud in place of the progress bar, which is decorative. Use {level} for the level and {ordinal} for first to fourth.', max_length=255)),
                ('skill_points_intro', models.CharField(default='You can:', help_text='Sentence the points under a skill read on from.', max_length=255)),
                ('related_roles_heading', models.CharField(default='Roles that share {role} skills', help_text='Heading over the roles sharing skills with this one.', max_length=255)),
                ('related_roles_table_role_heading', models.CharField(default='Role', help_text='First column of that table.', max_length=255)),
                ('related_roles_table_skills_heading', models.CharField(default='Shared skills', help_text='Second column of that table.', max_length=255)),
                ('progression_scs_roles_heading', models.CharField(default='Senior Civil Service roles that {role} could lead to', help_text='Heading over the senior roles this role leads on to.', max_length=255)),
                ('progression_roles_heading', models.CharField(default='Roles that could lead to {role}', help_text='Heading over the roles that lead into this one.', max_length=255)),
                ('updates_heading', models.CharField(default='Updates', help_text="Heading over a role's change history.", max_length=255)),
                ('published_prefix', models.CharField(default='Published', help_text='Shown before the date the role was first published.', max_length=255)),
                ('no_roles_message', models.CharField(default='No roles selected.', help_text='Shown on a role page with no role chosen and nothing written.', max_length=255)),
                ('scs_skill_label', models.CharField(default='Senior Civil Service', help_text='Shown beside a skill that only Senior Civil Service roles use.', max_length=255)),
                ('skill_leadership_examples_heading', models.CharField(default='Examples of leadership using this skill', help_text="Heading over a skill's leadership points on the skills page.", max_length=255)),
                ('skill_levels_table_level_heading', models.CharField(default='Skill level', help_text="First column of a skill's levels table.", max_length=255)),
                ('skill_levels_table_description_heading', models.CharField(default='Description', help_text='Second column of that table.', max_length=255)),
                ('skill_level_no_description_message', models.CharField(default='No description provided.', help_text='Shown where a skill level has had no points written for it.', max_length=255)),
                ('skill_roles_heading', models.CharField(default='Roles that require this skill', help_text='Heading over the roles that need a skill.', max_length=255)),
                ('no_skills_message', models.CharField(default='No skills found.', help_text='Shown on the skills page while no skills exist.', max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Capability framework wording',
                'verbose_name_plural': 'Capability framework wording',
            },
        ),
    ]
