# Generated by Django 6.0.8 on 2026-08-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0062_capabilityframeworkwordingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='capabilityframeworkwordingsettings',
            name='breadcrumb_home_label',
            field=models.CharField(default='Home', help_text='The first entry of the narrow-screen breadcrumb.', max_length=100),
        ),
        migrations.AddField(
            model_name='capabilityframeworkwordingsettings',
            name='further_resources_heading',
            field=models.CharField(default='Further resources', help_text="Heading over the navigation's non-role pages.", max_length=255),
        ),
        migrations.AddField(
            model_name='capabilityframeworkwordingsettings',
            name='hide_all_updates_link_text',
            field=models.CharField(default='- hide all updates', help_text="The link that closes the home page's update history.", max_length=100),
        ),
        migrations.AddField(
            model_name='capabilityframeworkwordingsettings',
            name='overview_heading_text',
            field=models.CharField(default='What {article} {role} does', help_text="Heading over a role's description. {article} is a or an.", max_length=255),
        ),
        migrations.AddField(
            model_name='capabilityframeworkwordingsettings',
            name='role_family_group_title',
            field=models.CharField(default='{family} roles', help_text="Title of each family's navigation group and home page section. {family} is the family's name from the role records.", max_length=255),
        ),
        migrations.AddField(
            model_name='capabilityframeworkwordingsettings',
            name='role_lead_text',
            field=models.CharField(default='Find out what {article} {role} in government does and the skills you need to do the role at each level.', help_text="The sentence under a role's heading.", max_length=500),
        ),
        migrations.AddField(
            model_name='capabilityframeworkwordingsettings',
            name='role_levels_described_many',
            field=models.CharField(default='The typical responsibilities and skills for each role level are described in the sections below.', help_text='Follows the opening for a role with several levels.', max_length=255),
        ),
        migrations.AddField(
            model_name='capabilityframeworkwordingsettings',
            name='role_levels_described_one',
            field=models.CharField(default='The typical responsibilities and skills for this role level are described below.', help_text='Follows the opening for a role with a single level.', max_length=255),
        ),
        migrations.AddField(
            model_name='capabilityframeworkwordingsettings',
            name='role_levels_opening_many',
            field=models.CharField(default='There are {count} {role} role levels{levels_range}.', help_text='Opens the levels section. {levels_range} is the from-to clause below, or nothing where the levels are unnamed.', max_length=255),
        ),
        migrations.AddField(
            model_name='capabilityframeworkwordingsettings',
            name='role_levels_opening_one',
            field=models.CharField(default='There is one {role} role level.', help_text='Opens the levels section for a role with a single level.', max_length=255),
        ),
        migrations.AddField(
            model_name='capabilityframeworkwordingsettings',
            name='role_levels_purpose_text',
            field=models.CharField(default='You can use this to identify the skills you need to progress in your career, or simply to learn more about each role in the Government Digital and Data profession.', help_text='Closes the sentence under the role levels heading.', max_length=500),
        ),
        migrations.AddField(
            model_name='capabilityframeworkwordingsettings',
            name='role_levels_range_text',
            field=models.CharField(default=', from {first} to {last}', help_text='The from-to clause naming the first and last role levels.', max_length=255),
        ),
        migrations.AddField(
            model_name='capabilityframeworkwordingsettings',
            name='scs_role_lead_text',
            field=models.CharField(default='Find out what {article} {role} in the Senior Civil Service does and the skills you need to do the role.', help_text="The sentence under a Senior Civil Service role's heading.", max_length=500),
        ),
        migrations.AddField(
            model_name='capabilityframeworkwordingsettings',
            name='show_all_updates_link_text',
            field=models.CharField(default='+ show all updates', help_text="The link that opens the home page's collapsed update history.", max_length=100),
        ),
    ]
