# Generated by Django 6.0.8 on 2026-08-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0063_capabilityframeworkwordingsettings_breadcrumb_home_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customisesettings',
            name='error_contact_about',
            field=models.CharField(blank=True, default='', help_text="What the reader would be speaking to someone about, closing the contact sentence: 'if you need to speak to someone about the …'.", max_length=255),
        ),
        migrations.AddField(
            model_name='customisesettings',
            name='error_contact_email',
            field=models.EmailField(blank=True, default='', help_text="Where the error pages' contact link points.", max_length=254),
        ),
        migrations.AddField(
            model_name='customisesettings',
            name='error_contact_link_text',
            field=models.CharField(blank=True, default='', help_text="Who the error pages offer to put a reader in touch with, for example a team's name. Leave blank for no contact sentence.", max_length=255),
        ),
    ]
