# Generated by Django 6.0.8 on 2026-08-27 17:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0065_editor_snippet_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='body_blocks',
            field=wagtail.fields.StreamField([('text', 0), ('table', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Text'}), 1: ('govuk.models.GovukTableBlock', (), {})}, help_text='Shown after the body above. To put a table part-way through a page, move the body text into a Text block here and add the table between the blocks.', verbose_name='Tables and further content'),
        ),
    ]
