# Generated by Django 6.0.7 on 2026-09-07 13:33

import django.db.models.deletion
import govuk.models
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0068_customisesettings_page_feedback_more_intro_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameworkContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('enable_hero_styling', models.BooleanField(default=False, help_text='When enabled, this page uses hero styling.', verbose_name='Enable hero styling')),
                ('enable_combined_service_navigation_and_hero_styling', models.BooleanField(default=False, help_text='When enabled, this page uses a combined service navigation and hero styling.', verbose_name='Enable combined service navigation and hero styling')),
                ('hero_title', models.CharField(blank=True, help_text='Optional hero heading. If blank, the page title is used.', max_length=255)),
                ('hero_intro', wagtail.fields.RichTextField(blank=True)),
                ('author', models.CharField(blank=True, default='', help_text='Optional author name displayed above the main content.', max_length=255)),
                ('show_last_updated_date', models.BooleanField(default=False, help_text='Show the page last updated date above the main content.', verbose_name='Show last updated date')),
                ('show_page_content_metadata', models.BooleanField(default=False, help_text='Show page metadata above the main content.', verbose_name='Show page content metadata')),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('body_blocks', wagtail.fields.StreamField([('text', 0), ('table', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Text'}), 1: ('govuk.models.GovukTableBlock', (), {})}, help_text='Shown after the body above. To put a table part-way through a page, move the body text into a Text block here and add the table between the blocks.', verbose_name='Tables and further content')),
                ('enable_free_text_heading_navigation', models.BooleanField(default=False, help_text='Show free text in a two-thirds and one-third layout with an automatic clickable heading list.', verbose_name='Enable sidebar heading navigation')),
                ('show_role_navigation', models.BooleanField(default=False, help_text='Show the list of roles grouped by family alongside the page, as the role pages do.', verbose_name='Show role navigation')),
                ('show_framework_updates', models.BooleanField(default=False, help_text='Show the changelog entries that are not tied to a single role or skill, with a last updated date above the page content.', verbose_name='Show framework updates')),
                ('show_framework_welcome', models.BooleanField(default=False, help_text="Show the framework's welcome text, with a contents list and the roles grouped by family for narrow screens.", verbose_name='Show framework welcome content')),
                ('framework_welcome_body', wagtail.fields.StreamField([('section', 4), ('skill_level_definitions', 13), ('section_break', 14), ('inset_text', 15)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section heading, for example How to use this framework.', 'max_length': 255}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Main section, listed in the contents'), ('h3', 'Sub-section, not listed in the contents')], 'help_text': 'Main sections appear in the contents list at the top of the page.'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional link target, for example capability-assessments. Defaults to the heading. Set one to keep existing links working if the heading is reworded.', 'max_length': 255, 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol', 'line-break'], 'help_text': "The section's prose."}), 4: ('wagtail.blocks.StructBlock', [[('heading', 0), ('level', 1), ('anchor', 2), ('body', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Skill level definitions', 'help_text': 'Table caption, read out by screen readers.', 'max_length': 255}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Skill level definitions', 'max_length': 255}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'What the level means', 'max_length': 255}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Level name, for example Awareness.', 'max_length': 100}), 9: ('wagtail.blocks.IntegerBlock', (), {'default': 1, 'help_text': 'How many of the 4 progress bar segments are filled, so awareness is 1 and expert is 4.', 'max_value': 4, 'min_value': 1}), 10: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol', 'line-break'], 'help_text': 'What someone at this level can do.'}), 11: ('wagtail.blocks.StructBlock', [[('name', 8), ('filled_segments', 9), ('description', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'help_text': 'One row per level, in ascending order.'}), 13: ('wagtail.blocks.StructBlock', [[('caption', 5), ('level_column_heading', 6), ('meaning_column_heading', 7), ('levels', 12)]], {}), 14: ('govuk.models.SectionBreakBlock', (), {}), 15: ('govuk.models.InsetTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol', 'line-break']})}, help_text="The welcome page's editorial content, shown when Show framework welcome content is switched on. The contents list is built from the main section headings.", verbose_name='Framework welcome content')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='FrameworkMainPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('enable_hero_styling', models.BooleanField(default=False, help_text='When enabled, this page uses hero styling.', verbose_name='Enable hero styling')),
                ('enable_combined_service_navigation_and_hero_styling', models.BooleanField(default=False, help_text='When enabled, this page uses a combined service navigation and hero styling.', verbose_name='Enable combined service navigation and hero styling')),
                ('hero_title', models.CharField(blank=True, help_text='Optional hero heading. If blank, the page title is used.', max_length=255)),
                ('hero_intro', wagtail.fields.RichTextField(blank=True)),
                ('author', models.CharField(blank=True, default='', help_text='Optional author name displayed above the main content.', max_length=255)),
                ('show_last_updated_date', models.BooleanField(default=False, help_text='Show the page last updated date above the main content.', verbose_name='Show last updated date')),
                ('show_page_content_metadata', models.BooleanField(default=False, help_text='Show page metadata above the main content.', verbose_name='Show page content metadata')),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('body_blocks', wagtail.fields.StreamField([('text', 0), ('table', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Text'}), 1: ('govuk.models.GovukTableBlock', (), {})}, help_text='Shown after the body above. To put a table part-way through a page, move the body text into a Text block here and add the table between the blocks.', verbose_name='Tables and further content')),
                ('enable_free_text_heading_navigation', models.BooleanField(default=False, help_text='Show free text in a two-thirds and one-third layout with an automatic clickable heading list.', verbose_name='Enable sidebar heading navigation')),
                ('show_role_navigation', models.BooleanField(default=False, help_text='Show the list of roles grouped by family alongside the page, as the role pages do.', verbose_name='Show role navigation')),
                ('show_framework_updates', models.BooleanField(default=False, help_text='Show the changelog entries that are not tied to a single role or skill, with a last updated date above the page content.', verbose_name='Show framework updates')),
                ('show_framework_welcome', models.BooleanField(default=False, help_text="Show the framework's welcome text, with a contents list and the roles grouped by family for narrow screens.", verbose_name='Show framework welcome content')),
                ('framework_welcome_body', wagtail.fields.StreamField([('section', 4), ('skill_level_definitions', 13), ('section_break', 14), ('inset_text', 15)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section heading, for example How to use this framework.', 'max_length': 255}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Main section, listed in the contents'), ('h3', 'Sub-section, not listed in the contents')], 'help_text': 'Main sections appear in the contents list at the top of the page.'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional link target, for example capability-assessments. Defaults to the heading. Set one to keep existing links working if the heading is reworded.', 'max_length': 255, 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol', 'line-break'], 'help_text': "The section's prose."}), 4: ('wagtail.blocks.StructBlock', [[('heading', 0), ('level', 1), ('anchor', 2), ('body', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Skill level definitions', 'help_text': 'Table caption, read out by screen readers.', 'max_length': 255}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Skill level definitions', 'max_length': 255}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'What the level means', 'max_length': 255}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Level name, for example Awareness.', 'max_length': 100}), 9: ('wagtail.blocks.IntegerBlock', (), {'default': 1, 'help_text': 'How many of the 4 progress bar segments are filled, so awareness is 1 and expert is 4.', 'max_value': 4, 'min_value': 1}), 10: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol', 'line-break'], 'help_text': 'What someone at this level can do.'}), 11: ('wagtail.blocks.StructBlock', [[('name', 8), ('filled_segments', 9), ('description', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'help_text': 'One row per level, in ascending order.'}), 13: ('wagtail.blocks.StructBlock', [[('caption', 5), ('level_column_heading', 6), ('meaning_column_heading', 7), ('levels', 12)]], {}), 14: ('govuk.models.SectionBreakBlock', (), {}), 15: ('govuk.models.InsetTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol', 'line-break']})}, help_text="The welcome page's editorial content, shown when Show framework welcome content is switched on. The contents list is built from the main section headings.", verbose_name='Framework welcome content')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, govuk.models.RoleRenderingMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='FrameworkContentPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='govuk.frameworkcontentpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framework_content_page_tagged_items', to='govuk.govuktag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='frameworkcontentpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='govuk.FrameworkContentPageTag', to='govuk.GovukTag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='FrameworkMainPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='govuk.frameworkmainpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framework_main_page_tagged_items', to='govuk.govuktag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='frameworkmainpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='govuk.FrameworkMainPageTag', to='govuk.GovukTag', verbose_name='Tags'),
        ),
    ]
