# Generated by Django 6.0.8 on 2026-09-08 15:00

from django.conf import settings
from django.db import migrations, models


# The pages the live service lists at the foot of its role side menu, by slug.
# Before this migration the group was every page beside the roles, so on a
# framework instance these five were already listed (with others that should
# not have been). Ticking them here keeps the menu matching live through the
# deploy; an editor can untick any of them afterwards. Only on a site running
# the framework, and only for direct children of a site's home page, so no
# other site's content is touched.
LIVE_SIDE_MENU_SLUGS = (
    "propose-a-change",
    "download",
    "job-grades",
    "context-and-challenges-for-senior-civil-service-roles-in-digital-and-data",
    "roadmap",
)


def tick_the_live_pages(apps, schema_editor):
    if not settings.FEATURE_FLAGS.get("SKILLS"):
        return
    Site = apps.get_model("wagtailcore", "Site")
    ContentPage = apps.get_model("govuk", "ContentPage")
    for site in Site.objects.select_related("root_page"):
        root = site.root_page
        ContentPage.objects.filter(
            path__startswith=root.path,
            depth=root.depth + 1,
            slug__in=LIVE_SIDE_MENU_SLUGS,
        ).update(show_in_role_navigation=True)


def untick(apps, schema_editor):
    ContentPage = apps.get_model("govuk", "ContentPage")
    ContentPage.objects.filter(slug__in=LIVE_SIDE_MENU_SLUGS).update(
        show_in_role_navigation=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0068_customisesettings_page_feedback_more_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='show_in_role_navigation',
            field=models.BooleanField(default=False, help_text='List this page under the last heading of the role side menu, after the role families, on every page that shows the menu. Skills A to Z is always listed. This is separate from Show in menus on the Promote tab, which controls the header.', verbose_name='List in the role side menu'),
        ),
        migrations.RunPython(tick_the_live_pages, untick),
    ]
