# Generated by Django 6.0.8 on 2026-09-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0069_contentpage_show_in_role_navigation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customisesettings',
            name='page_feedback_more_intro',
            field=models.CharField(blank=True, default='To help improve the framework, we’d like to know more about your visit today.', help_text='The sentence shown after someone answers, above the link.', max_length=255, verbose_name='Feedback follow-up sentence'),
        ),
        migrations.AlterField(
            model_name='customisesettings',
            name='page_feedback_more_link_text',
            field=models.CharField(blank=True, default='Give more feedback on using the framework website', help_text='The wording of the link shown after someone answers.', max_length=255, verbose_name='Feedback follow-up link text'),
        ),
        migrations.AlterField(
            model_name='customisesettings',
            name='page_feedback_more_url',
            field=models.CharField(blank=True, default='/feedback', help_text='Where "Give more feedback" points after someone answers, for example a survey. Defaults to /feedback.', max_length=500, verbose_name='Feedback follow-up link'),
        ),
        migrations.AlterField(
            model_name='customisesettings',
            name='show_page_feedback_prompt',
            field=models.BooleanField(default=False, help_text='Ask "Is this page useful?" at the foot of every page, as GOV.UK publications do. Answers are recorded in the server logs.', verbose_name='Ask "Is this page useful?" on every page'),
        ),
    ]
