# Generated by Django 6.0.7 on 2026-09-08 17:37

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models

import govuk.models


def _framework_columns(ContentPage):
    """Columns shared between ContentPage and the framework page types.

    At this point in the migration, ContentPage also has show_in_role_navigation
    (added by 0069) which the framework page types do not, so that column is
    excluded from the copy.
    """
    excluded = {"show_in_role_navigation"}
    return [
        field.column
        for field in ContentPage._meta.local_fields
        if field.column not in excluded
    ]


def _convert_page(cursor, qn, *, page_id, source_table, target_table, columns, extra_fields=None):
    col_sql = ", ".join(qn(c) for c in columns)
    cursor.execute(
        f"SELECT {col_sql} FROM {qn(source_table)} WHERE {qn('page_ptr_id')} = %s",
        [page_id],
    )
    row = cursor.fetchone()
    if row is None:
        return

    all_columns = list(columns)
    all_values = list(row)
    if extra_fields:
        for col, val in extra_fields.items():
            all_columns.append(col)
            all_values.append(val)

    all_col_sql = ", ".join(qn(c) for c in all_columns)
    all_ph = ", ".join(["%s"] * len(all_columns))
    cursor.execute(
        f"INSERT INTO {qn(target_table)} ({all_col_sql}) VALUES ({all_ph})",
        all_values,
    )
    cursor.execute(
        f"DELETE FROM {qn(source_table)} WHERE {qn('page_ptr_id')} = %s",
        [page_id],
    )


def _migrate_tags(*, page_id, SourceTag, TargetTag):
    tag_ids = list(
        SourceTag.objects.filter(content_object_id=page_id).values_list("tag_id", flat=True)
    )
    for tag_id in tag_ids:
        TargetTag.objects.create(content_object_id=page_id, tag_id=tag_id)
    SourceTag.objects.filter(content_object_id=page_id).delete()


def convert_framework_contentpages(apps, schema_editor):
    """Convert ContentPages that have framework switches on to the new types.

    The shallowest such page becomes the single FrameworkMainPage; the rest
    become FrameworkContentPage children under it.  Pages without any framework
    switch are left as ContentPages.
    """
    from django.db.models import Q

    ContentType = apps.get_model("contenttypes", "ContentType")
    Page = apps.get_model("wagtailcore", "Page")
    ContentPage = apps.get_model("govuk", "ContentPage")
    FrameworkMainPage = apps.get_model("govuk", "FrameworkMainPage")
    FrameworkContentPage = apps.get_model("govuk", "FrameworkContentPage")
    ContentPageTag = apps.get_model("govuk", "ContentPageTag")
    FrameworkMainPageTag = apps.get_model("govuk", "FrameworkMainPageTag")
    FrameworkContentPageTag = apps.get_model("govuk", "FrameworkContentPageTag")

    db_alias = schema_editor.connection.alias

    framework_page_ids = list(
        ContentPage.objects.using(db_alias)
        .filter(Q(show_role_navigation=True) | Q(show_framework_updates=True) | Q(show_framework_welcome=True))
        .values_list("page_ptr_id", flat=True)
    )
    if not framework_page_ids:
        return

    ordered = list(
        Page.objects.using(db_alias)
        .filter(id__in=framework_page_ids)
        .order_by("depth", "path")
        .values_list("id", "path")
    )
    main_page_id = ordered[0][0]
    content_page_ids = [pid for pid, _ in ordered[1:]]

    main_ct, _ = ContentType.objects.using(db_alias).get_or_create(
        app_label="govuk", model="frameworkmainpage"
    )
    content_ct, _ = ContentType.objects.using(db_alias).get_or_create(
        app_label="govuk", model="frameworkcontentpage"
    )

    columns = _framework_columns(ContentPage)
    source_table = ContentPage._meta.db_table
    qn = schema_editor.connection.ops.quote_name

    with schema_editor.connection.cursor() as cursor:
        _convert_page(
            cursor, qn,
            page_id=main_page_id,
            source_table=source_table,
            target_table=FrameworkMainPage._meta.db_table,
            columns=columns,
        )
        for page_id in content_page_ids:
            _convert_page(
                cursor, qn,
                page_id=page_id,
                source_table=source_table,
                target_table=FrameworkContentPage._meta.db_table,
                columns=columns,
                # show_in_framework_navigation is in the FrameworkContentPage
                # CreateModel but not in ContentPage — supply the default.
                extra_fields={"show_in_framework_navigation": True},
            )

    from wagtail.models import Page as WagtailPage
    WagtailPage.objects.using(db_alias).filter(id=main_page_id).update(
        content_type_id=main_ct.id
    )
    WagtailPage.objects.using(db_alias).filter(id__in=content_page_ids).update(
        content_type_id=content_ct.id
    )

    _migrate_tags(page_id=main_page_id, SourceTag=ContentPageTag, TargetTag=FrameworkMainPageTag)
    for page_id in content_page_ids:
        _migrate_tags(page_id=page_id, SourceTag=ContentPageTag, TargetTag=FrameworkContentPageTag)

    # Reparent any framework content page not already under the main page.
    main_page = WagtailPage.objects.using(db_alias).filter(id=main_page_id).first()
    if main_page:
        for page_id in content_page_ids:
            page = WagtailPage.objects.using(db_alias).filter(id=page_id).first()
            if page and not page.path.startswith(main_page.path):
                page.move(main_page, pos="last-child")

    # Re-index each converted page so its reference-index rows point at its new
    # type, keeping the welcome body's references usable in the admin.
    try:
        from wagtail.models import ReferenceIndex
    except ImportError:
        ReferenceIndex = None
    if ReferenceIndex is not None:
        for page_id in [main_page_id, *content_page_ids]:
            page = WagtailPage.objects.using(db_alias).filter(id=page_id).first()
            if page is not None:
                ReferenceIndex.create_or_update_for_object(page.specific)


def clear_stale_contentpage_references(apps, schema_editor):
    """Drop reference-index rows that point at ContentPage.framework_welcome_body.

    This migration removes that field from ContentPage.  Any reference-index row
    still typed as ContentPage with a framework_welcome_body path — from a page
    that carried welcome-body content but was not converted, or one re-indexing
    did not cover — raises FieldDoesNotExist when Wagtail resolves it (e.g. on
    the page-delete confirmation).  Correct rows for the converted pages are now
    typed FrameworkMainPage/FrameworkContentPage and are left untouched;
    ``rebuild_references_index`` restores anything dropped here.
    """
    ContentType = apps.get_model("contenttypes", "ContentType")
    db_alias = schema_editor.connection.alias

    try:
        ReferenceIndex = apps.get_model("wagtailcore", "ReferenceIndex")
    except LookupError:
        return

    contentpage_ct = (
        ContentType.objects.using(db_alias)
        .filter(app_label="govuk", model="contentpage")
        .first()
    )
    if contentpage_ct is None:
        return

    ReferenceIndex.objects.using(db_alias).filter(
        content_type_id=contentpage_ct.id,
        model_path__startswith="framework_welcome_body",
    ).delete()


def delete_rolepages(apps, schema_editor):
    """Delete every RolePage row without using the ORM cascade collector.

    The cascade collector queries ALL MTI child models in the current registry —
    including FrameworkSkillsPage whose table doesn't exist yet — so raw SQL is
    used throughout.
    """
    ContentType = apps.get_model("contenttypes", "ContentType")
    RolePage = apps.get_model("govuk", "RolePage")
    RolePageTag = apps.get_model("govuk", "RolePageTag")
    db_alias = schema_editor.connection.alias
    conn = schema_editor.connection
    qn = conn.ops.quote_name

    rolepage_ct = (
        ContentType.objects.using(db_alias)
        .filter(app_label="govuk", model="rolepage")
        .first()
    )
    if rolepage_ct is None:
        return

    with conn.cursor() as cursor:
        cursor.execute(
            "SELECT id, path FROM wagtailcore_page WHERE content_type_id = %s",
            [rolepage_ct.id],
        )
        role_rows = cursor.fetchall()

    if not role_rows:
        return

    role_ids = [row[0] for row in role_rows]
    role_paths = [row[1] for row in role_rows]
    ph = ", ".join(["%s"] * len(role_ids))

    RolePageTag.objects.using(db_alias).filter(content_object_id__in=role_ids).delete()

    existing_tables = set(conn.introspection.table_names())

    with conn.cursor() as cursor:
        cursor.execute(
            f"DELETE FROM {qn(RolePage._meta.db_table)} "
            f"WHERE {qn('page_ptr_id')} IN ({ph})",
            role_ids,
        )
        for table, fk_col in [
            ("wagtailcore_pagelogentry", "page_id"),
            ("wagtailcore_pageviewrestriction", "page_id"),
            ("wagtailcore_comment", "page_id"),
            ("wagtailcore_grouppagepermission", "page_id"),
            ("wagtailcore_workflowpage", "page_id"),
            ("wagtailcore_pagesubscription", "page_id"),
            ("wagtailforms_formsubmission", "page_id"),
            ("wagtailredirects_redirect", "redirect_page_id"),
        ]:
            if table in existing_tables:
                cursor.execute(
                    f"DELETE FROM {qn(table)} WHERE {qn(fk_col)} IN ({ph})",
                    role_ids,
                )
        cursor.execute(
            f"UPDATE wagtailcore_page SET alias_of_id = NULL "
            f"WHERE alias_of_id IN ({ph})",
            role_ids,
        )
        for path in role_paths:
            if len(path) > 4:
                cursor.execute(
                    "UPDATE wagtailcore_page SET numchild = numchild - 1 "
                    "WHERE path = %s AND numchild > 0",
                    [path[:-4]],
                )
        cursor.execute(
            f"DELETE FROM wagtailcore_page WHERE id IN ({ph})",
            role_ids,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0070_page_feedback_field_labels'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameworkContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('enable_hero_styling', models.BooleanField(default=False, help_text='When enabled, this page uses hero styling.', verbose_name='Enable hero styling')),
                ('enable_combined_service_navigation_and_hero_styling', models.BooleanField(default=False, help_text='When enabled, this page uses a combined service navigation and hero styling.', verbose_name='Enable combined service navigation and hero styling')),
                ('hero_title', models.CharField(blank=True, help_text='Optional hero heading. If blank, the page title is used.', max_length=255)),
                ('hero_intro', wagtail.fields.RichTextField(blank=True)),
                ('author', models.CharField(blank=True, default='', help_text='Optional author name displayed above the main content.', max_length=255)),
                ('show_last_updated_date', models.BooleanField(default=False, help_text='Show the page last updated date above the main content.', verbose_name='Show last updated date')),
                ('show_page_content_metadata', models.BooleanField(default=False, help_text='Show page metadata above the main content.', verbose_name='Show page content metadata')),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('body_blocks', wagtail.fields.StreamField([('text', 0), ('table', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Text'}), 1: ('govuk.models.GovukTableBlock', (), {})}, help_text='Shown after the body above. To put a table part-way through a page, move the body text into a Text block here and add the table between the blocks.', verbose_name='Tables and further content')),
                ('enable_free_text_heading_navigation', models.BooleanField(default=False, help_text='Show free text in a two-thirds and one-third layout with an automatic clickable heading list.', verbose_name='Enable sidebar heading navigation')),
                ('show_role_navigation', models.BooleanField(default=True, help_text='Show the list of roles grouped by family alongside the page, as the role pages do.', verbose_name='Show role navigation')),
                ('show_framework_updates', models.BooleanField(default=True, help_text='Show the changelog entries that are not tied to a single role or skill, with a last updated date above the page content.', verbose_name='Show framework updates')),
                ('show_framework_welcome', models.BooleanField(default=True, help_text="Show the framework's welcome text, with a contents list and the roles grouped by family for narrow screens.", verbose_name='Show framework welcome content')),
                ('framework_welcome_body', wagtail.fields.StreamField([('section', 4), ('skill_level_definitions', 13), ('section_break', 14), ('inset_text', 15)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section heading, for example How to use this framework.', 'max_length': 255}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Main section, listed in the contents'), ('h3', 'Sub-section, not listed in the contents')], 'help_text': 'Main sections appear in the contents list at the top of the page.'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional link target, for example capability-assessments. Defaults to the heading. Set one to keep existing links working if the heading is reworded.', 'max_length': 255, 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol', 'line-break'], 'help_text': "The section's prose."}), 4: ('wagtail.blocks.StructBlock', [[('heading', 0), ('level', 1), ('anchor', 2), ('body', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Skill level definitions', 'help_text': 'Table caption, read out by screen readers.', 'max_length': 255}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Skill level definitions', 'max_length': 255}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'What the level means', 'max_length': 255}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Level name, for example Awareness.', 'max_length': 100}), 9: ('wagtail.blocks.IntegerBlock', (), {'default': 1, 'help_text': 'How many of the 4 progress bar segments are filled, so awareness is 1 and expert is 4.', 'max_value': 4, 'min_value': 1}), 10: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol', 'line-break'], 'help_text': 'What someone at this level can do.'}), 11: ('wagtail.blocks.StructBlock', [[('name', 8), ('filled_segments', 9), ('description', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'help_text': 'One row per level, in ascending order.'}), 13: ('wagtail.blocks.StructBlock', [[('caption', 5), ('level_column_heading', 6), ('meaning_column_heading', 7), ('levels', 12)]], {}), 14: ('govuk.models.SectionBreakBlock', (), {}), 15: ('govuk.models.InsetTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol', 'line-break']})}, help_text="The welcome page's editorial content, shown when Show framework welcome content is switched on. The contents list is built from the main section headings.", verbose_name='Framework welcome content')),
                ('show_in_framework_navigation', models.BooleanField(default=True, help_text="List this page in the framework's sidebar navigation, under Further resources. On by default.", verbose_name='Show in sidebar navigation')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='FrameworkMainPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('enable_hero_styling', models.BooleanField(default=False, help_text='When enabled, this page uses hero styling.', verbose_name='Enable hero styling')),
                ('enable_combined_service_navigation_and_hero_styling', models.BooleanField(default=False, help_text='When enabled, this page uses a combined service navigation and hero styling.', verbose_name='Enable combined service navigation and hero styling')),
                ('hero_title', models.CharField(blank=True, help_text='Optional hero heading. If blank, the page title is used.', max_length=255)),
                ('hero_intro', wagtail.fields.RichTextField(blank=True)),
                ('author', models.CharField(blank=True, default='', help_text='Optional author name displayed above the main content.', max_length=255)),
                ('show_last_updated_date', models.BooleanField(default=False, help_text='Show the page last updated date above the main content.', verbose_name='Show last updated date')),
                ('show_page_content_metadata', models.BooleanField(default=False, help_text='Show page metadata above the main content.', verbose_name='Show page content metadata')),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('body_blocks', wagtail.fields.StreamField([('text', 0), ('table', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Text'}), 1: ('govuk.models.GovukTableBlock', (), {})}, help_text='Shown after the body above. To put a table part-way through a page, move the body text into a Text block here and add the table between the blocks.', verbose_name='Tables and further content')),
                ('enable_free_text_heading_navigation', models.BooleanField(default=False, help_text='Show free text in a two-thirds and one-third layout with an automatic clickable heading list.', verbose_name='Enable sidebar heading navigation')),
                ('show_role_navigation', models.BooleanField(default=True, help_text='Show the list of roles grouped by family alongside the page, as the role pages do.', verbose_name='Show role navigation')),
                ('show_framework_updates', models.BooleanField(default=True, help_text='Show the changelog entries that are not tied to a single role or skill, with a last updated date above the page content.', verbose_name='Show framework updates')),
                ('show_framework_welcome', models.BooleanField(default=True, help_text="Show the framework's welcome text, with a contents list and the roles grouped by family for narrow screens.", verbose_name='Show framework welcome content')),
                ('framework_welcome_body', wagtail.fields.StreamField([('section', 4), ('skill_level_definitions', 13), ('section_break', 14), ('inset_text', 15)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section heading, for example How to use this framework.', 'max_length': 255}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Main section, listed in the contents'), ('h3', 'Sub-section, not listed in the contents')], 'help_text': 'Main sections appear in the contents list at the top of the page.'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional link target, for example capability-assessments. Defaults to the heading. Set one to keep existing links working if the heading is reworded.', 'max_length': 255, 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol', 'line-break'], 'help_text': "The section's prose."}), 4: ('wagtail.blocks.StructBlock', [[('heading', 0), ('level', 1), ('anchor', 2), ('body', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Skill level definitions', 'help_text': 'Table caption, read out by screen readers.', 'max_length': 255}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Skill level definitions', 'max_length': 255}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'What the level means', 'max_length': 255}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Level name, for example Awareness.', 'max_length': 100}), 9: ('wagtail.blocks.IntegerBlock', (), {'default': 1, 'help_text': 'How many of the 4 progress bar segments are filled, so awareness is 1 and expert is 4.', 'max_value': 4, 'min_value': 1}), 10: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol', 'line-break'], 'help_text': 'What someone at this level can do.'}), 11: ('wagtail.blocks.StructBlock', [[('name', 8), ('filled_segments', 9), ('description', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'help_text': 'One row per level, in ascending order.'}), 13: ('wagtail.blocks.StructBlock', [[('caption', 5), ('level_column_heading', 6), ('meaning_column_heading', 7), ('levels', 12)]], {}), 14: ('govuk.models.SectionBreakBlock', (), {}), 15: ('govuk.models.InsetTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol', 'line-break']})}, help_text="The welcome page's editorial content, shown when Show framework welcome content is switched on. The contents list is built from the main section headings.", verbose_name='Framework welcome content')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, govuk.models.RoleRenderingMixin, 'wagtailcore.page', models.Model),
        ),
        # Rename the existing Skills A to Z page rather than dropping and
        # recreating it, so its page (and any content) is preserved. The only
        # new column is show_in_framework_navigation, added straight after.
        migrations.RenameModel(
            old_name='SkillsAZPage',
            new_name='FrameworkSkillsPage',
        ),
        migrations.AddField(
            model_name='frameworkskillspage',
            name='show_in_framework_navigation',
            field=models.BooleanField(default=True, help_text="List this page in the framework's sidebar navigation, under Further resources. On by default.", verbose_name='Show in sidebar navigation'),
        ),
        # Tag models created here so they exist when the RunPython below runs.
        migrations.CreateModel(
            name='FrameworkContentPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='govuk.frameworkcontentpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framework_content_page_tagged_items', to='govuk.govuktag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='frameworkcontentpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='govuk.FrameworkContentPageTag', to='govuk.GovukTag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='FrameworkMainPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='govuk.frameworkmainpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framework_main_page_tagged_items', to='govuk.govuktag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='frameworkmainpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='govuk.FrameworkMainPageTag', to='govuk.GovukTag', verbose_name='Tags'),
        ),
        migrations.AlterModelOptions(
            name='phasebannersettings',
            options={'verbose_name': 'Phase banner'},
        ),
        # Convert any ContentPages that have framework switches on before their
        # shared columns are removed.  The three framework page types are all
        # created above, so the target tables exist at this point.
        migrations.RunPython(
            convert_framework_contentpages,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            delete_rolepages,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='framework_welcome_body',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='show_framework_updates',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='show_framework_welcome',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='show_in_role_navigation',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='show_role_navigation',
        ),
        migrations.RemoveField(
            model_name='customisesettings',
            name='hero_background_color',
        ),
        migrations.RemoveField(
            model_name='customisesettings',
            name='hero_text_color',
        ),
        migrations.RemoveField(
            model_name='customisesettings',
            name='hide_sign_in_link',
        ),
        migrations.RemoveField(
            model_name='customisesettings',
            name='show_service_name_in_navigation',
        ),
        migrations.AddField(
            model_name='customisesettings',
            name='search_location',
            field=models.CharField(choices=[('header', 'Header bar'), ('navigation', 'Service navigation'), ('hidden', 'Hidden')], default='header', help_text='Where the search box appears.', max_length=20),
        ),
        migrations.AddField(
            model_name='customisesettings',
            name='service_name_location',
            field=models.CharField(choices=[('header', 'Header bar'), ('navigation', 'Service navigation')], default='header', help_text='Where the service name appears.', max_length=20),
        ),
        migrations.AddField(
            model_name='customisesettings',
            name='sign_in_location',
            field=models.CharField(choices=[('header', 'Header bar'), ('navigation', 'Service navigation'), ('hidden', 'Hidden')], default='navigation', help_text='Where the sign in and sign out links appear. Choose Hidden for sites where visitors never sign in -- the sign in link is hidden, but a signed-in user can still sign out.', max_length=20),
        ),
        # RolePageTag fields removed after delete_rolepages has used them.
        migrations.RemoveField(
            model_name='rolepagetag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='rolepagetag',
            name='tag',
        ),
        migrations.DeleteModel(
            name='RolePage',
        ),
        migrations.DeleteModel(
            name='RolePageTag',
        ),
        # Field is gone now; drop any reference-index rows that still point at
        # ContentPage.framework_welcome_body so the admin can resolve references.
        migrations.RunPython(
            clear_stale_contentpage_references,
            migrations.RunPython.noop,
        ),
    ]
