# Generated by Django 6.0.7 on 2026-09-08 17:37

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models

import govuk.models


def _framework_columns(ContentPage):
    """Columns shared between ContentPage and the framework page types.

    At this point in the migration, ContentPage also has show_in_role_navigation
    (added by 0069) which the framework page types do not, so that column is
    excluded from the copy.
    """
    excluded = {"show_in_role_navigation"}
    return [
        field.column
        for field in ContentPage._meta.local_fields
        if field.column not in excluded
    ]


def _convert_page(cursor, qn, *, page_id, source_table, target_table, columns, extra_fields=None):
    col_sql = ", ".join(qn(c) for c in columns)
    cursor.execute(
        f"SELECT {col_sql} FROM {qn(source_table)} WHERE {qn('page_ptr_id')} = %s",
        [page_id],
    )
    row = cursor.fetchone()
    if row is None:
        return

    all_columns = list(columns)
    all_values = list(row)
    if extra_fields:
        for col, val in extra_fields.items():
            all_columns.append(col)
            all_values.append(val)

    all_col_sql = ", ".join(qn(c) for c in all_columns)
    all_ph = ", ".join(["%s"] * len(all_columns))
    cursor.execute(
        f"INSERT INTO {qn(target_table)} ({all_col_sql}) VALUES ({all_ph})",
        all_values,
    )
    cursor.execute(
        f"DELETE FROM {qn(source_table)} WHERE {qn('page_ptr_id')} = %s",
        [page_id],
    )


def _migrate_tags(*, page_id, SourceTag, TargetTag):
    tag_ids = list(
        SourceTag.objects.filter(content_object_id=page_id).values_list("tag_id", flat=True)
    )
    for tag_id in tag_ids:
        TargetTag.objects.create(content_object_id=page_id, tag_id=tag_id)
    SourceTag.objects.filter(content_object_id=page_id).delete()


def convert_framework_contentpages(apps, schema_editor):
    """Convert ContentPages that have framework switches on to the new types.

    The shallowest page with a framework switch on becomes the single
    FrameworkMainPage. Every other page with a switch on, and every page ticked
    for the role side menu (``show_in_role_navigation``, which 0069 set on the
    five pages the live service lists there), becomes a FrameworkContentPage
    under it. Pages with neither are left as ContentPages.

    The tick counts because it is the editors' record of which pages belong
    beside the roles. On the development instance only two of live's five
    side-menu pages have a switch on; the other three were put in the menu by
    the tick alone, and reading only the switches would drop them from the
    menu on upgrade. The page import applies the same rule to a file from
    before this migration, so the two paths agree.
    """
    from django.db.models import Q

    ContentType = apps.get_model("contenttypes", "ContentType")
    Page = apps.get_model("wagtailcore", "Page")
    ContentPage = apps.get_model("govuk", "ContentPage")
    FrameworkMainPage = apps.get_model("govuk", "FrameworkMainPage")
    FrameworkContentPage = apps.get_model("govuk", "FrameworkContentPage")
    ContentPageTag = apps.get_model("govuk", "ContentPageTag")
    FrameworkMainPageTag = apps.get_model("govuk", "FrameworkMainPageTag")
    FrameworkContentPageTag = apps.get_model("govuk", "FrameworkContentPageTag")

    db_alias = schema_editor.connection.alias

    switch_page_ids = list(
        ContentPage.objects.using(db_alias)
        .filter(Q(show_role_navigation=True) | Q(show_framework_updates=True) | Q(show_framework_welcome=True))
        .values_list("page_ptr_id", flat=True)
    )
    if not switch_page_ids:
        # A ticked page with no main page to sit under stays as it is: a
        # FrameworkContentPage needs the framework, and there is none here.
        return

    ordered = list(
        Page.objects.using(db_alias)
        .filter(id__in=switch_page_ids)
        .order_by("depth", "path")
        .values_list("id", "path")
    )
    # The default site's home page is the main page when it carries a switch,
    # which on the Capability Framework it does. Only otherwise does the
    # shallowest switched page win -- a stray switched page beside the home
    # page with an earlier path must not become the framework's root and have
    # the real home page moved underneath it.
    Site = apps.get_model("wagtailcore", "Site")
    default_root_id = (
        Site.objects.using(db_alias)
        .filter(is_default_site=True)
        .values_list("root_page_id", flat=True)
        .first()
    )
    main_page_id = default_root_id if default_root_id in switch_page_ids else ordered[0][0]
    ticked_page_ids = list(
        ContentPage.objects.using(db_alias)
        .filter(show_in_role_navigation=True)
        .exclude(page_ptr_id__in=switch_page_ids)
        .values_list("page_ptr_id", flat=True)
    )
    content_page_ids = list(
        Page.objects.using(db_alias)
        .filter(id__in=[pid for pid, _ in ordered if pid != main_page_id] + ticked_page_ids)
        .order_by("depth", "path")
        .values_list("id", flat=True)
    )

    main_ct, _ = ContentType.objects.using(db_alias).get_or_create(
        app_label="govuk", model="frameworkmainpage"
    )
    content_ct, _ = ContentType.objects.using(db_alias).get_or_create(
        app_label="govuk", model="frameworkcontentpage"
    )

    columns = _framework_columns(ContentPage)
    source_table = ContentPage._meta.db_table
    qn = schema_editor.connection.ops.quote_name

    with schema_editor.connection.cursor() as cursor:
        _convert_page(
            cursor, qn,
            page_id=main_page_id,
            source_table=source_table,
            target_table=FrameworkMainPage._meta.db_table,
            columns=columns,
        )
        for page_id in content_page_ids:
            _convert_page(
                cursor, qn,
                page_id=page_id,
                source_table=source_table,
                target_table=FrameworkContentPage._meta.db_table,
                columns=columns,
                # show_in_framework_navigation is in the FrameworkContentPage
                # CreateModel but not in ContentPage — supply the default.
                extra_fields={"show_in_framework_navigation": True},
            )

    from wagtail.models import Page as WagtailPage
    WagtailPage.objects.using(db_alias).filter(id=main_page_id).update(
        content_type_id=main_ct.id
    )
    WagtailPage.objects.using(db_alias).filter(id__in=content_page_ids).update(
        content_type_id=content_ct.id
    )

    _migrate_tags(page_id=main_page_id, SourceTag=ContentPageTag, TargetTag=FrameworkMainPageTag)
    for page_id in content_page_ids:
        _migrate_tags(page_id=page_id, SourceTag=ContentPageTag, TargetTag=FrameworkContentPageTag)

    # Reparent any framework content page not already under the main page.
    main_page = WagtailPage.objects.using(db_alias).filter(id=main_page_id).first()
    if main_page:
        for page_id in content_page_ids:
            page = WagtailPage.objects.using(db_alias).filter(id=page_id).first()
            if page and not page.path.startswith(main_page.path):
                page.move(main_page, pos="last-child")

    # Re-index each converted page so its reference-index rows point at its new
    # type, keeping the welcome body's references usable in the admin.
    try:
        from wagtail.models import ReferenceIndex
    except ImportError:
        ReferenceIndex = None
    if ReferenceIndex is not None:
        for page_id in [main_page_id, *content_page_ids]:
            page = WagtailPage.objects.using(db_alias).filter(id=page_id).first()
            if page is not None:
                ReferenceIndex.create_or_update_for_object(page.specific)


def delete_rolepages(apps, schema_editor):
    """Delete every RolePage row without using the ORM cascade collector.

    The cascade collector queries ALL MTI child models in the current registry —
    including FrameworkSkillsPage whose table doesn't exist yet — so raw SQL is
    used throughout.
    """
    ContentType = apps.get_model("contenttypes", "ContentType")
    RolePage = apps.get_model("govuk", "RolePage")
    RolePageTag = apps.get_model("govuk", "RolePageTag")
    db_alias = schema_editor.connection.alias
    conn = schema_editor.connection
    qn = conn.ops.quote_name

    rolepage_ct = (
        ContentType.objects.using(db_alias)
        .filter(app_label="govuk", model="rolepage")
        .first()
    )
    if rolepage_ct is None:
        return

    with conn.cursor() as cursor:
        cursor.execute(
            "SELECT id, path, numchild FROM wagtailcore_page WHERE content_type_id = %s",
            [rolepage_ct.id],
        )
        role_rows = cursor.fetchall()

    if not role_rows:
        return

    # A role page could hold child pages. Deleting it by raw SQL would leave
    # them in the tree under a path that no longer exists: unreachable, but
    # counted, and a trap for the next tree repair. No instance has any, and
    # rather than guess what to do with one this stops the migration -- and so
    # the container -- with a message naming the pages, before anything is
    # changed. Move or delete them in the admin, then deploy again.
    with_children = [row[0] for row in role_rows if row[2]]
    if with_children:
        raise RuntimeError(
            "Migration 0071 cannot delete role pages that have child pages "
            f"(page ids {with_children}). Move or delete the children in the "
            "admin first."
        )

    role_ids = [row[0] for row in role_rows]
    role_paths = [row[1] for row in role_rows]
    ph = ", ".join(["%s"] * len(role_ids))
    # Revisions, workflow state, the search index and the reference index name
    # a page by content type and a *string* object id rather than by a page
    # foreign key, so the ORM cascade that would normally clear them does not
    # apply and they are named here. Left behind they are not inert: a revision
    # for a page that no longer exists surfaces in the admin's history views
    # and reports, and a stale reference-index row raises when Wagtail resolves
    # it.
    object_ids = [str(role_id) for role_id in role_ids]
    page_ct = (
        ContentType.objects.using(db_alias)
        .filter(app_label="wagtailcore", model="page")
        .first()
    )
    content_type_ids = [rolepage_ct.id] + ([page_ct.id] if page_ct else [])
    ct_ph = ", ".join(["%s"] * len(content_type_ids))

    RolePageTag.objects.using(db_alias).filter(content_object_id__in=role_ids).delete()

    existing_tables = set(conn.introspection.table_names())

    with conn.cursor() as cursor:
        cursor.execute(
            f"DELETE FROM {qn(RolePage._meta.db_table)} "
            f"WHERE {qn('page_ptr_id')} IN ({ph})",
            role_ids,
        )
        # Rows that hang off rows deleted below, so they go first.
        if "wagtailcore_pageviewrestriction_groups" in existing_tables:
            cursor.execute(
                f"DELETE FROM wagtailcore_pageviewrestriction_groups WHERE "
                f"pageviewrestriction_id IN (SELECT id FROM "
                f"wagtailcore_pageviewrestriction WHERE page_id IN ({ph}))",
                role_ids,
            )
        if "wagtailcore_commentreply" in existing_tables:
            cursor.execute(
                f"DELETE FROM wagtailcore_commentreply WHERE comment_id IN "
                f"(SELECT id FROM wagtailcore_comment WHERE page_id IN ({ph}))",
                role_ids,
            )
        if "wagtailcore_taskstate" in existing_tables:
            cursor.execute(
                f"DELETE FROM wagtailcore_taskstate WHERE workflow_state_id IN "
                f"(SELECT id FROM wagtailcore_workflowstate "
                f"WHERE content_type_id IN ({ct_ph}) AND object_id IN ({ph}))",
                [*content_type_ids, *object_ids],
            )
            cursor.execute(
                f"DELETE FROM wagtailcore_taskstate WHERE revision_id IN "
                f"(SELECT id FROM wagtailcore_revision "
                f"WHERE content_type_id IN ({ct_ph}) AND object_id IN ({ph}))",
                [*content_type_ids, *object_ids],
            )
        for table, fk_col in [
            ("wagtailcore_pagelogentry", "page_id"),
            ("wagtailcore_pageviewrestriction", "page_id"),
            ("wagtailcore_comment", "page_id"),
            ("wagtailcore_grouppagepermission", "page_id"),
            ("wagtailcore_workflowpage", "page_id"),
            ("wagtailcore_pagesubscription", "page_id"),
            ("wagtailforms_formsubmission", "page_id"),
            # A redirect that pointed at a role page points at nothing now. The
            # role is served at the live service's own URL (role/<slug>/ on the
            # framework main page), so when the main page is the site's home
            # page no replacement is needed; anywhere else,
            # `seed_live_service_redirects` writes the link redirects.
            ("wagtailredirects_redirect", "redirect_page_id"),
        ]:
            if table in existing_tables:
                cursor.execute(
                    f"DELETE FROM {qn(table)} WHERE {qn(fk_col)} IN ({ph})",
                    role_ids,
                )
        for table in (
            "wagtailcore_workflowstate",
            "wagtailcore_revision",
            "wagtailcore_referenceindex",
            "wagtailsearch_indexentry",
            "wagtailadmin_editingsession",
        ):
            if table in existing_tables:
                cursor.execute(
                    f"DELETE FROM {qn(table)} "
                    f"WHERE content_type_id IN ({ct_ph}) AND object_id IN ({ph})",
                    [*content_type_ids, *object_ids],
                )
        if "wagtailcore_referenceindex" in existing_tables:
            # Rows pointing *at* a role page from elsewhere (a welcome-page
            # link, a related role), which would otherwise resolve to nothing.
            cursor.execute(
                f"DELETE FROM wagtailcore_referenceindex "
                f"WHERE to_content_type_id IN ({ct_ph}) AND to_object_id IN ({ph})",
                [*content_type_ids, *object_ids],
            )
        cursor.execute(
            f"UPDATE wagtailcore_page SET alias_of_id = NULL "
            f"WHERE alias_of_id IN ({ph})",
            role_ids,
        )
        for path in role_paths:
            if len(path) > 4:
                cursor.execute(
                    "UPDATE wagtailcore_page SET numchild = numchild - 1 "
                    "WHERE path = %s AND numchild > 0",
                    [path[:-4]],
                )
        cursor.execute(
            f"DELETE FROM wagtailcore_page WHERE id IN ({ph})",
            role_ids,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0070_page_feedback_field_labels'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameworkContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('enable_hero_styling', models.BooleanField(default=False, help_text='When enabled, this page uses hero styling.', verbose_name='Enable hero styling')),
                ('enable_combined_service_navigation_and_hero_styling', models.BooleanField(default=False, help_text='When enabled, this page uses a combined service navigation and hero styling.', verbose_name='Enable combined service navigation and hero styling')),
                ('hero_title', models.CharField(blank=True, help_text='Optional hero heading. If blank, the page title is used.', max_length=255)),
                ('hero_intro', wagtail.fields.RichTextField(blank=True)),
                ('author', models.CharField(blank=True, default='', help_text='Optional author name displayed above the main content.', max_length=255)),
                ('show_last_updated_date', models.BooleanField(default=False, help_text='Show the page last updated date above the main content.', verbose_name='Show last updated date')),
                ('show_page_content_metadata', models.BooleanField(default=False, help_text='Show page metadata above the main content.', verbose_name='Show page content metadata')),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('body_blocks', wagtail.fields.StreamField([('text', 0), ('table', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Text'}), 1: ('govuk.models.GovukTableBlock', (), {})}, help_text='Shown after the body above. To put a table part-way through a page, move the body text into a Text block here and add the table between the blocks.', verbose_name='Tables and further content')),
                ('enable_free_text_heading_navigation', models.BooleanField(default=False, help_text='Show free text in a two-thirds and one-third layout with an automatic clickable heading list.', verbose_name='Enable sidebar heading navigation')),
                ('show_role_navigation', models.BooleanField(default=True, help_text='Show the list of roles grouped by family alongside the page, as the role pages do.', verbose_name='Show role navigation')),
                ('show_framework_updates', models.BooleanField(default=True, help_text='Show the changelog entries that are not tied to a single role or skill, with a last updated date above the page content.', verbose_name='Show framework updates')),
                ('show_framework_welcome', models.BooleanField(default=True, help_text="Show the framework's welcome text, with a contents list and the roles grouped by family for narrow screens.", verbose_name='Show framework welcome content')),
                ('framework_welcome_body', wagtail.fields.StreamField([('section', 4), ('skill_level_definitions', 13), ('section_break', 14), ('inset_text', 15)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section heading, for example How to use this framework.', 'max_length': 255}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Main section, listed in the contents'), ('h3', 'Sub-section, not listed in the contents')], 'help_text': 'Main sections appear in the contents list at the top of the page.'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional link target, for example capability-assessments. Defaults to the heading. Set one to keep existing links working if the heading is reworded.', 'max_length': 255, 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol', 'line-break'], 'help_text': "The section's prose."}), 4: ('wagtail.blocks.StructBlock', [[('heading', 0), ('level', 1), ('anchor', 2), ('body', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Skill level definitions', 'help_text': 'Table caption, read out by screen readers.', 'max_length': 255}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Skill level definitions', 'max_length': 255}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'What the level means', 'max_length': 255}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Level name, for example Awareness.', 'max_length': 100}), 9: ('wagtail.blocks.IntegerBlock', (), {'default': 1, 'help_text': 'How many of the 4 progress bar segments are filled, so awareness is 1 and expert is 4.', 'max_value': 4, 'min_value': 1}), 10: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol', 'line-break'], 'help_text': 'What someone at this level can do.'}), 11: ('wagtail.blocks.StructBlock', [[('name', 8), ('filled_segments', 9), ('description', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'help_text': 'One row per level, in ascending order.'}), 13: ('wagtail.blocks.StructBlock', [[('caption', 5), ('level_column_heading', 6), ('meaning_column_heading', 7), ('levels', 12)]], {}), 14: ('govuk.models.SectionBreakBlock', (), {}), 15: ('govuk.models.InsetTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol', 'line-break']})}, help_text="The welcome page's editorial content, shown when Show framework welcome content is switched on. The contents list is built from the main section headings.", verbose_name='Framework welcome content')),
                ('show_in_framework_navigation', models.BooleanField(default=True, help_text="List this page in the framework's sidebar navigation, under Further resources. On by default.", verbose_name='Show in sidebar navigation')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='FrameworkMainPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('enable_hero_styling', models.BooleanField(default=False, help_text='When enabled, this page uses hero styling.', verbose_name='Enable hero styling')),
                ('enable_combined_service_navigation_and_hero_styling', models.BooleanField(default=False, help_text='When enabled, this page uses a combined service navigation and hero styling.', verbose_name='Enable combined service navigation and hero styling')),
                ('hero_title', models.CharField(blank=True, help_text='Optional hero heading. If blank, the page title is used.', max_length=255)),
                ('hero_intro', wagtail.fields.RichTextField(blank=True)),
                ('author', models.CharField(blank=True, default='', help_text='Optional author name displayed above the main content.', max_length=255)),
                ('show_last_updated_date', models.BooleanField(default=False, help_text='Show the page last updated date above the main content.', verbose_name='Show last updated date')),
                ('show_page_content_metadata', models.BooleanField(default=False, help_text='Show page metadata above the main content.', verbose_name='Show page content metadata')),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('body_blocks', wagtail.fields.StreamField([('text', 0), ('table', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Text'}), 1: ('govuk.models.GovukTableBlock', (), {})}, help_text='Shown after the body above. To put a table part-way through a page, move the body text into a Text block here and add the table between the blocks.', verbose_name='Tables and further content')),
                ('enable_free_text_heading_navigation', models.BooleanField(default=False, help_text='Show free text in a two-thirds and one-third layout with an automatic clickable heading list.', verbose_name='Enable sidebar heading navigation')),
                ('show_role_navigation', models.BooleanField(default=True, help_text='Show the list of roles grouped by family alongside the page, as the role pages do.', verbose_name='Show role navigation')),
                ('show_framework_updates', models.BooleanField(default=True, help_text='Show the changelog entries that are not tied to a single role or skill, with a last updated date above the page content.', verbose_name='Show framework updates')),
                ('show_framework_welcome', models.BooleanField(default=True, help_text="Show the framework's welcome text, with a contents list and the roles grouped by family for narrow screens.", verbose_name='Show framework welcome content')),
                ('framework_welcome_body', wagtail.fields.StreamField([('section', 4), ('skill_level_definitions', 13), ('section_break', 14), ('inset_text', 15)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section heading, for example How to use this framework.', 'max_length': 255}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Main section, listed in the contents'), ('h3', 'Sub-section, not listed in the contents')], 'help_text': 'Main sections appear in the contents list at the top of the page.'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional link target, for example capability-assessments. Defaults to the heading. Set one to keep existing links working if the heading is reworded.', 'max_length': 255, 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol', 'line-break'], 'help_text': "The section's prose."}), 4: ('wagtail.blocks.StructBlock', [[('heading', 0), ('level', 1), ('anchor', 2), ('body', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Skill level definitions', 'help_text': 'Table caption, read out by screen readers.', 'max_length': 255}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Skill level definitions', 'max_length': 255}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'What the level means', 'max_length': 255}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Level name, for example Awareness.', 'max_length': 100}), 9: ('wagtail.blocks.IntegerBlock', (), {'default': 1, 'help_text': 'How many of the 4 progress bar segments are filled, so awareness is 1 and expert is 4.', 'max_value': 4, 'min_value': 1}), 10: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol', 'line-break'], 'help_text': 'What someone at this level can do.'}), 11: ('wagtail.blocks.StructBlock', [[('name', 8), ('filled_segments', 9), ('description', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'help_text': 'One row per level, in ascending order.'}), 13: ('wagtail.blocks.StructBlock', [[('caption', 5), ('level_column_heading', 6), ('meaning_column_heading', 7), ('levels', 12)]], {}), 14: ('govuk.models.SectionBreakBlock', (), {}), 15: ('govuk.models.InsetTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol', 'line-break']})}, help_text="The welcome page's editorial content, shown when Show framework welcome content is switched on. The contents list is built from the main section headings.", verbose_name='Framework welcome content')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, govuk.models.RoleRenderingMixin, 'wagtailcore.page', models.Model),
        ),
        # Rename the existing Skills A to Z page rather than dropping and
        # recreating it, so its page (and any content) is preserved. The only
        # new column is show_in_framework_navigation, added straight after.
        migrations.RenameModel(
            old_name='SkillsAZPage',
            new_name='FrameworkSkillsPage',
        ),
        migrations.AddField(
            model_name='frameworkskillspage',
            name='show_in_framework_navigation',
            field=models.BooleanField(default=True, help_text="List this page in the framework's sidebar navigation, under Further resources. On by default.", verbose_name='Show in sidebar navigation'),
        ),
        # Tag models created here so they exist when the RunPython below runs.
        migrations.CreateModel(
            name='FrameworkContentPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='govuk.frameworkcontentpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framework_content_page_tagged_items', to='govuk.govuktag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='frameworkcontentpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='govuk.FrameworkContentPageTag', to='govuk.GovukTag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='FrameworkMainPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='govuk.frameworkmainpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framework_main_page_tagged_items', to='govuk.govuktag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='frameworkmainpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='govuk.FrameworkMainPageTag', to='govuk.GovukTag', verbose_name='Tags'),
        ),
        migrations.AlterModelOptions(
            name='phasebannersettings',
            options={'verbose_name': 'Phase banner'},
        ),
        # Convert any ContentPages that have framework switches on before their
        # shared columns are removed.  The three framework page types are all
        # created above, so the target tables exist at this point.
        migrations.RunPython(
            convert_framework_contentpages,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            delete_rolepages,
            migrations.RunPython.noop,
        ),
    ]
