# Generated by Django 6.0.7 on 2026-09-09 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0072_remove_frameworkcontentpage_show_in_framework_navigation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customisesettings',
            name='content_max_width',
            field=models.PositiveIntegerField(blank=True, help_text='How wide the page content grows on large screens, in pixels. Leave blank for the default of 950.', null=True, validators=[django.core.validators.MinValueValidator(320), django.core.validators.MaxValueValidator(2560)], verbose_name='Maximum content width (pixels)'),
        ),
        migrations.AlterField(
            model_name='customisesettings',
            name='extra_css',
            field=models.TextField(blank=True, default='', help_text='Optional additional CSS appended after other overrides.'),
        ),
    ]
