# Generated by Django 6.0.7 on 2026-09-08 23:12

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


def seed_hidden_pages(apps, schema_editor):
    """Preserve any page currently hidden from the sidebar.

    The per-page show_in_framework_navigation flag is being removed in favour of
    Sidebar settings, where an unlisted page is shown by default. So a page that
    was explicitly hidden (flag False) needs an explicit "not visible" row to
    keep it hidden. Runs before the flag is dropped; a no-op on a fresh database.
    """
    Site = apps.get_model("wagtailcore", "Site")
    FrameworkContentPage = apps.get_model("govuk", "FrameworkContentPage")
    FrameworkSkillsPage = apps.get_model("govuk", "FrameworkSkillsPage")
    SidebarSettings = apps.get_model("govuk", "SidebarSettings")
    SidebarNavigationItem = apps.get_model("govuk", "SidebarNavigationItem")
    db_alias = schema_editor.connection.alias

    hidden_page_ids = list(
        FrameworkContentPage.objects.using(db_alias)
        .filter(show_in_framework_navigation=False)
        .values_list("page_ptr_id", flat=True)
    )
    hidden_page_ids += list(
        FrameworkSkillsPage.objects.using(db_alias)
        .filter(show_in_framework_navigation=False)
        .values_list("page_ptr_id", flat=True)
    )
    if not hidden_page_ids:
        return

    site = Site.objects.using(db_alias).filter(is_default_site=True).first()
    if site is None:
        return

    setting, _ = SidebarSettings.objects.using(db_alias).get_or_create(site=site)
    for order, page_id in enumerate(hidden_page_ids):
        SidebarNavigationItem.objects.using(db_alias).create(
            setting=setting, page_id=page_id, visible=False, sort_order=order
        )


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0072_remove_legacy_framework_fields_and_rolepage'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Sidebar settings',
                'verbose_name_plural': 'Sidebar settings',
            },
        ),
        migrations.CreateModel(
            name='SidebarNavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('visible', models.BooleanField(default=True, help_text='Untick to hide this page from the sidebar without removing it.')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
                ('setting', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='govuk.sidebarsettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        # Seed hidden rows before the flag is dropped, so a page that was
        # explicitly hidden stays hidden under the new "shown by default" rule.
        migrations.RunPython(seed_hidden_pages, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='frameworkcontentpage',
            name='show_in_framework_navigation',
        ),
        migrations.RemoveField(
            model_name='frameworkskillspage',
            name='show_in_framework_navigation',
        ),
    ]
