# Generated by Django 6.0.7 on 2026-09-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0074_reference_index_cleanup'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkillsAZPage',
            new_name='FrameworkSkillsPage',
        ),
    ]
