# Generated by Django 6.1.1 on 2026-09-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0075_customisesettings_enable_search_results_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customisesettings',
            name='show_back_to_top',
            field=models.BooleanField(default=False, help_text='Offer a “Back to top” link once the reader has scrolled past the first screen of a long page, as GOV.UK guidance pages do. It appears only where JavaScript can reveal it, so it is never offered where it could not work.', verbose_name='Show a “Back to top” link'),
        ),
    ]
