# Generated by Django 6.0.7 on 2026-09-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0075_rename_skillsazpage_frameworkskillspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameworkcontentpage',
            name='show_framework_updates',
            field=models.BooleanField(default=True, help_text='Show the changelog entries that are not tied to a single role or skill, with a last updated date above the page content.', verbose_name='Show framework updates'),
        ),
        migrations.AlterField(
            model_name='frameworkcontentpage',
            name='show_framework_welcome',
            field=models.BooleanField(default=True, help_text="Show the framework's welcome text, with a contents list and the roles grouped by family for narrow screens.", verbose_name='Show framework welcome content'),
        ),
        migrations.AlterField(
            model_name='frameworkcontentpage',
            name='show_role_navigation',
            field=models.BooleanField(default=True, help_text='Show the list of roles grouped by family alongside the page, as the role pages do.', verbose_name='Show role navigation'),
        ),
        migrations.AlterField(
            model_name='frameworkmainpage',
            name='show_framework_updates',
            field=models.BooleanField(default=True, help_text='Show the changelog entries that are not tied to a single role or skill, with a last updated date above the page content.', verbose_name='Show framework updates'),
        ),
        migrations.AlterField(
            model_name='frameworkmainpage',
            name='show_framework_welcome',
            field=models.BooleanField(default=True, help_text="Show the framework's welcome text, with a contents list and the roles grouped by family for narrow screens.", verbose_name='Show framework welcome content'),
        ),
        migrations.AlterField(
            model_name='frameworkmainpage',
            name='show_role_navigation',
            field=models.BooleanField(default=True, help_text='Show the list of roles grouped by family alongside the page, as the role pages do.', verbose_name='Show role navigation'),
        ),
    ]
