# Generated by Django 6.1.1 on 2026-09-21 16:29

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


def copy_error_contact_to_error_pages(apps, schema_editor):
    """Carry a site's error-contact wording from Customise into Error pages.

    The three fields moved model, so an instance that already had them set
    keeps its values: copy them into the (just created) Error pages setting
    for the same site before the old columns are dropped below.
    """
    CustomiseSettings = apps.get_model("govuk", "CustomiseSettings")
    ErrorPagesSettings = apps.get_model("govuk", "ErrorPagesSettings")
    for customise in CustomiseSettings.objects.all():
        error_pages, _ = ErrorPagesSettings.objects.get_or_create(
            site=customise.site
        )
        error_pages.error_contact_link_text = customise.error_contact_link_text
        error_pages.error_contact_email = customise.error_contact_email
        error_pages.error_contact_about = customise.error_contact_about
        error_pages.save()


def copy_error_contact_back(apps, schema_editor):
    """Reverse: put the wording back on Customise before its columns go."""
    CustomiseSettings = apps.get_model("govuk", "CustomiseSettings")
    ErrorPagesSettings = apps.get_model("govuk", "ErrorPagesSettings")
    for error_pages in ErrorPagesSettings.objects.all():
        try:
            customise = CustomiseSettings.objects.get(site=error_pages.site)
        except CustomiseSettings.DoesNotExist:
            continue
        customise.error_contact_link_text = error_pages.error_contact_link_text
        customise.error_contact_email = error_pages.error_contact_email
        customise.error_contact_about = error_pages.error_contact_about
        customise.save()


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0076_customisesettings_show_back_to_top'),
        ('wagtailcore', '0098_apitoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customisesettings',
            name='show_back_to_top',
            field=models.BooleanField(default=False, help_text='Offer a “Back to top” link at the bottom-left of the page once the reader has scrolled past the first screen of a long page.', verbose_name='Show a “Back to top” link'),
        ),
        migrations.CreateModel(
            name='ErrorPagesSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_found_heading', models.CharField(blank=True, default='Page not found', help_text="The heading on the page a reader reaches when a web address does not exist. Leave blank for the Design System's “Page not found”.", max_length=255, verbose_name='Page not found: heading')),
                ('not_found_body', wagtail.fields.RichTextField(blank=True, default='<p>If you typed the web address, check it is correct.</p><p>If you pasted the web address, check you copied the entire address.</p>', help_text='What the page not found page says above the contact sentence. Clear it to say nothing. The contact sentence below is added separately.', verbose_name='Page not found: body')),
                ('problem_heading', models.CharField(blank=True, default='Sorry, there is a problem with the service', help_text="The heading on the page a reader reaches when the service hits an error. Leave blank for the Design System's “Sorry, there is a problem with the service”.", max_length=255, verbose_name='Problem with the service: heading')),
                ('problem_body', wagtail.fields.RichTextField(blank=True, default='<p>Try again later.</p>', help_text='What the problem page says above the contact sentence. Clear it to say nothing. The contact sentence below is added separately.', verbose_name='Problem with the service: body')),
                ('unavailable_heading', models.CharField(blank=True, default='Sorry, the service is unavailable', help_text="The heading on the page a reader reaches while the service is closed for maintenance. Leave blank for the Design System's “Sorry, the service is unavailable”.", max_length=255, verbose_name='Service unavailable: heading')),
                ('unavailable_body', wagtail.fields.RichTextField(blank=True, default='<p>You will be able to use the service later.</p>', help_text='What the unavailable page says above the contact sentence when no maintenance return time is set. Clear it to say nothing. The contact sentence below is added separately.', verbose_name='Service unavailable: body')),
                ('error_contact_link_text', models.CharField(blank=True, default='', help_text="Who the error pages offer to put a reader in touch with, for example a team's name. Leave blank for no contact sentence.", max_length=255)),
                ('error_contact_email', models.EmailField(blank=True, default='', help_text="Where the error pages' contact link points.", max_length=254)),
                ('error_contact_about', models.CharField(blank=True, default='', help_text="What the reader would be speaking to someone about, closing the contact sentence: 'if you need to speak to someone about the …'.", max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Error pages',
                'verbose_name_plural': 'Error pages',
            },
        ),
        migrations.RunPython(
            copy_error_contact_to_error_pages,
            copy_error_contact_back,
        ),
        migrations.RemoveField(
            model_name='customisesettings',
            name='error_contact_about',
        ),
        migrations.RemoveField(
            model_name='customisesettings',
            name='error_contact_email',
        ),
        migrations.RemoveField(
            model_name='customisesettings',
            name='error_contact_link_text',
        ),
    ]
