# Generated by Django 6.1.1 on 2026-09-21 15:18

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0076_customisesettings_show_back_to_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='customisesettings',
            name='not_found_body',
            field=wagtail.fields.RichTextField(blank=True, default='<p>If you typed the web address, check it is correct.</p><p>If you pasted the web address, check you copied the entire address.</p>', help_text='What the page not found page says above the contact sentence. Clear it to say nothing. The contact sentence below is added separately.', verbose_name='Page not found: body'),
        ),
        migrations.AddField(
            model_name='customisesettings',
            name='not_found_heading',
            field=models.CharField(blank=True, default='Page not found', help_text="The heading on the page a reader reaches when a web address does not exist. Leave blank for the Design System's “Page not found”.", max_length=255, verbose_name='Page not found: heading'),
        ),
        migrations.AlterField(
            model_name='customisesettings',
            name='show_back_to_top',
            field=models.BooleanField(default=False, help_text='Offer a “Back to top” link at the bottom-left of the page once the reader has scrolled past the first screen of a long page.', verbose_name='Show a “Back to top” link'),
        ),
    ]
