# Generated by Django 6.0.7 on 2026-09-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0076_alter_frameworkcontentpage_show_framework_updates_and_more'),
    ]

    operations = [
        # frameworkcontentpage.show_in_framework_navigation is added in 0069
        # (alongside the CreateModel) so it exists before 0071 deletes role
        # pages via the ORM collector, which would otherwise fail with
        # "no such column" when the collector queries FrameworkContentPage.
        migrations.AddField(
            model_name='frameworkskillspage',
            name='show_in_framework_navigation',
            field=models.BooleanField(default=True, help_text="List this page in the framework's sidebar navigation, under Further resources. On by default.", verbose_name='Show in sidebar navigation'),
        ),
    ]
