# Generated by Django 6.0.7 on 2026-09-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0076_alter_frameworkcontentpage_show_framework_updates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frameworkcontentpage',
            name='show_in_framework_navigation',
            field=models.BooleanField(default=True, help_text="List this page in the framework's sidebar navigation, under Further resources. On by default.", verbose_name='Show in sidebar navigation'),
        ),
        migrations.AddField(
            model_name='frameworkskillspage',
            name='show_in_framework_navigation',
            field=models.BooleanField(default=True, help_text="List this page in the framework's sidebar navigation, under Further resources. On by default.", verbose_name='Show in sidebar navigation'),
        ),
    ]
