# Generated by Django 6.0.7 on 2026-09-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0077_frameworkcontentpage_show_in_framework_navigation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customisesettings',
            name='hide_sign_in_link',
        ),
        migrations.RemoveField(
            model_name='customisesettings',
            name='show_service_name_in_navigation',
        ),
        migrations.AddField(
            model_name='customisesettings',
            name='search_location',
            field=models.CharField(choices=[('header', 'Header bar'), ('navigation', 'Service navigation'), ('hidden', 'Hidden')], default='header', help_text='Where the search box appears.', max_length=20),
        ),
        migrations.AddField(
            model_name='customisesettings',
            name='service_name_location',
            field=models.CharField(choices=[('header', 'Header bar'), ('navigation', 'Service navigation')], default='header', help_text='Where the service name appears.', max_length=20),
        ),
        migrations.AddField(
            model_name='customisesettings',
            name='sign_in_location',
            field=models.CharField(choices=[('header', 'Header bar'), ('navigation', 'Service navigation'), ('hidden', 'Hidden')], default='navigation', help_text='Where the sign in and sign out links appear. Choose Hidden for sites where visitors never sign in -- the sign in link is hidden, but a signed-in user can still sign out.', max_length=20),
        ),
    ]
