# Generated by Django 6.0.7 on 2026-09-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0078_remove_customisesettings_hide_sign_in_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phasebannersettings',
            options={'verbose_name': 'Phase banner'},
        ),
        migrations.RemoveField(
            model_name='customisesettings',
            name='hero_background_color',
        ),
        migrations.RemoveField(
            model_name='customisesettings',
            name='hero_text_color',
        ),
    ]
