# Generated by Django 6.1.1 on 2026-09-24 17:14

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


def copy_wording_to_maintenance(apps, schema_editor):
    """Carry each site's existing 503 wording into the new setting.

    The heading and body have moved out of ErrorPagesSettings and into
    MaintenanceModeSettings; without this an editor's customised wording would
    silently revert to the Design System defaults on migrate.
    """
    ErrorPagesSettings = apps.get_model("govuk", "ErrorPagesSettings")
    MaintenanceModeSettings = apps.get_model("govuk", "MaintenanceModeSettings")
    for error_pages in ErrorPagesSettings.objects.all():
        MaintenanceModeSettings.objects.update_or_create(
            site_id=error_pages.site_id,
            defaults={
                "heading": error_pages.unavailable_heading,
                "body": error_pages.unavailable_body,
                "enabled": False,
            },
        )


def copy_wording_back_to_error_pages(apps, schema_editor):
    """Reverse: put the wording back on ErrorPagesSettings."""
    ErrorPagesSettings = apps.get_model("govuk", "ErrorPagesSettings")
    MaintenanceModeSettings = apps.get_model("govuk", "MaintenanceModeSettings")
    for maintenance in MaintenanceModeSettings.objects.all():
        ErrorPagesSettings.objects.filter(site_id=maintenance.site_id).update(
            unavailable_heading=maintenance.heading,
            unavailable_body=maintenance.body,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0078_pageusefulnessvote'),
        ('wagtailcore', '0098_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceModeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Close the site behind the service-unavailable page. Signed-in users are still let through; the health check and admin stay open.', verbose_name='Maintenance mode')),
                ('heading', models.CharField(blank=True, default='Sorry, the service is unavailable', help_text="The heading on the page a reader reaches while the service is closed for maintenance. Leave blank for the Design System's “Sorry, the service is unavailable”.", max_length=255, verbose_name='Service unavailable: heading')),
                ('body', wagtail.fields.RichTextField(blank=True, default='<p>You will be able to use the service later.</p>', help_text='What the unavailable page says above the contact sentence when no maintenance return time is set. Clear it to say nothing. The contact sentence below is added separately.', verbose_name='Service unavailable: body')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Maintenance mode',
                'verbose_name_plural': 'Maintenance mode',
            },
        ),
        migrations.RunPython(
            copy_wording_to_maintenance,
            copy_wording_back_to_error_pages,
        ),
        migrations.RemoveField(
            model_name='errorpagessettings',
            name='unavailable_body',
        ),
        migrations.RemoveField(
            model_name='errorpagessettings',
            name='unavailable_heading',
        ),
    ]
