# Generated by Django 6.1.1 on 2026-09-25 09:47

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govuk', '0081_assign_workflow_to_roles_and_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorpagessettings',
            name='no_access_body',
            field=wagtail.fields.RichTextField(blank=True, default="<p>You are signed in, but your account does not have access to this resource.</p>", help_text='What the no-access page says above the contact sentence. Clear it to say nothing. The contact sentence below is added separately.', verbose_name='No access: body'),
        ),
        migrations.AddField(
            model_name='errorpagessettings',
            name='no_access_heading',
            field=models.CharField(blank=True, default='You do not have access', help_text='The heading on the page a signed-in reader reaches when they open the admin but have no CMS access. Leave blank for the default.', max_length=255, verbose_name='No access: heading'),
        ),
    ]
